OregonDigital/OD2

.dockerignore, .gitignore, Gemfile.lock, db/schema.rb, docker-compose.override.yml-example, docker-compose.yml
- Ignores potentially huge stuff when building docker images, stolen from @revgum 
- No ports are exposed by `docker-compose.yml`; devs can copy `docker-compose.override.yml-example` to `docker-compose.override.yml` (or create their own) to customize ports as it makes sense
=> Fix docker

.gitignore, Gemfile, Gemfile.lock, config/puma/development.rb, docker-compose.override.yml-example
Gems for remote debugging, and an example override for running the server in debug mode. 
Thrashed around a lot with this until I figured out that puma, running with workers, was the underlying problem preventing the remote debugging from working properly.
=> adds configuration to allow for remote debugging the web app in a docker container

Dockerfile
The idea here is to have easy access to vim when opening a shell for troubleshooting a running container, I think the image size is well worth the addition.
=> adds vim to docker image for debug/troubleshooting purposes

config/environments/development.rb
adds 192.* addresses to webconsole in development
=> allows docker containers to use webconsole in development

docker-compose.yml
The `cloud` style of Solr needs to persist more than just the cores for Docker.
=> persists solr server between uses

.gitignore, build/entrypoint.sh, build/install_gems.sh, docker-compose.yml
Fixes a bug that @decimalator ran into where a fresh repo didn't include the tmp/pids directory and caused docker to fail startup. 
Creates a single entrypoint script to run any bootstrap needs for development and test environments
=> fixes empty tmp/pids bug and makes entrypoint a single script

Dockerfile, build/entrypoint.sh, build/install_gems.sh
This gives the build server the ability to generate Docker images for staging and production environments (without dev/test gems which can cause problems, like having `spring` in the mix).
`.env` automatically sets the RAILS_ENV to development locally, otherwise to build production (`docker build --build-arg RAILS_ENV=production .`)
=> makes entrypoint more dynamic and allows for production or staging builds

app/actors/hyrax/actors/audio_actor.rb, app/controllers/hyrax/audios_controller.rb, app/forms/hyrax/audio_form.rb, app/indexers/audio_indexer.rb, app/models/audio.rb, app/models/video.rb, app/presenters/hyrax/audio_presenter.rb, app/views/hyrax/audios/_audio.html.erb, config/initializers/hyrax.rb, config/locales/audio.de.yml, config/locales/audio.en.yml, config/locales/audio.es.yml, config/locales/audio.fr.yml, config/locales/audio.it.yml, config/locales/audio.pt-BR.yml, config/locales/audio.zh.yml, spec/actors/hyrax/actors/audio_actor_spec.rb, spec/controllers/hyrax/audios_controller_spec.rb, spec/forms/hyrax/audio_form_spec.rb, spec/models/audio_spec.rb, spec/models/image_spec.rb, spec/models/video_spec.rb, spec/presenters/hyrax/audio_presenter_spec.rb, spec/system/create_audio_spec.rb, spec/system/create_document_spec.rb, spec/system/create_generic_spec.rb, spec/system/create_image_spec.rb, spec/system/create_video_spec.rb
fixes #109 
Customize metadata given [Metadata Application Profile](https://docs.google.com/spreadsheets/d/16xBFjmeSsaN0xQrbOpQ_jIOeFZk3ZM9kmB8CU3IhP2c/edit#gid=0)
=> add audio model and model specs

.circleci/config.yml, Gemfile, app/controllers/application_controller.rb, config.ru, docker-compose.yml
Honeycomb.init has to be called before the Rails environment, but the HONEYCOMB_DEBUG environment variable existence will disable it from sending traces and redirects that output to STDERR. 
This PR gives us the ability to enable it for development, if needed, but defaults both development and test to disabling it.. while enabling and initializing it for production/staging.
=> initializes honeycomb proper, disables integration for development/test env

build/entrypoint.sh
these markers add context to honeycomb for the boot process during deployment
fixes #175
=> posts markers to honeycomb during staging/production boot

Dockerfile
This ensures that the gems are only having to do a full rebuild when the
Gemfile* changes, rather than on every data change
=> Run bundler (in image) prior to adding all code

config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb
Disable email functionality for development, only spool the emails to the actionmailer array.
Updates staging and production to match the ENV for deployment.
=> Smtp configs

app/views/devise/shared/_links.html.erb
Fixes #259
QA: Go to devise login page and links for UO and OSU should be labeled correctly.
=> fixes login link on devise page

Gemfile, Gemfile.lock, app/controllers/application_controller.rb
fixes #188 
Requires a `docker-compose build`
=> pins to newer rack-honeycomb to keep from leaking login credentials

config/environments/production.rb, config/environments/staging.rb
fixes #213 
Staging had a configuration to force emails to not send because of the configuration `:test`.. This update puts the smtp enable as an ENV to allow for configurability for production and staging.
=> manages smtp to be enabled by env

docker-compose.yml
Ensures that gems are the same in dev and test, and "docker-compose run"
gets the same gems as "docker-compose exec"
=> Persist bundled gems

spec/forms/hyrax/audio_form_spec.rb, spec/forms/hyrax/document_form_spec.rb, spec/forms/hyrax/generic_form_spec.rb, spec/forms/hyrax/image_form_spec.rb, spec/forms/hyrax/video_form_spec.rb
Fixes #308, increases amount of metadata covered, and narrows terms searched to only those that actually appear on the form.
=> More closely match form spec to form-model relationship

app/controllers/users/omniauth_callbacks_controller.rb, config/initializers/devise.rb
This PR updates devise/omniauth config to correctly grab UO uids and match the entityID with the url most users will initiate SAML auth from.
It also disables CSRF checks for the SAML callback as the devise, omniauth, omniauth-saml stack does not implement CSRF challenges for that endpoint.
=> UO SAML fixes

.rubocop.yml, .rubocop_fixme.yml, app/controllers/hyrax/contact_form_controller.rb, lib/oregon_digital/triple_powered_properties/triplestore.rb, lib/oregon_digital/triple_powered_properties/work_indexer.rb, spec/controllers/hyrax/contact_form_controller_spec.rb, spec/controllers/oregon_digital/oembeds_controller_spec.rb, spec/controllers/users/omniauth_callbacks_controller_spec.rb, spec/factories/file_sets.rb, spec/models/user_spec.rb, spec/oregon_digital/triple_powered_properties/triplestore_spec.rb, spec/oregon_digital/triple_powered_properties/work_indexer_spec.rb, spec/search_builders/oregon_digital/errored_oembed_search_builder_spec.rb, spec/search_builders/oregon_digital/oembed_search_builder_spec.rb, spec/services/oregon_digital/user_attribute_service_spec.rb
linelength poll suggests that we disable the cop.. 
oddly, rubocop also found a bunch of offenses that I fixed.. wonder why those were caught in CCI
=> remove linelength, autofixes offenses

.rubocop_fixme.yml, app/models/generic.rb, lib/oregon_digital/controlled_vocabularies/resource.rb, spec/oregon_digital/controlled_vocabularies/resource_spec.rb
Fixes #335 
Originally 20135c0 was going to add typical validation behavior, but ActiveFedora doesn't seem to validate properties on works. Enter f1d6651 to run validation on controlled vocabulary properties, but then ActiveTriples doesn't support validation on ActiveTriples::BufferedTransaction.
I still think above is the preferable way to approach this, but d2ac188 just implements it similar to how OD1 did, w/ throwing an exception when a term is being fetched.
=> URI validation for Controlled Vocabularies

.circleci/config.yml, Dockerfile, Gemfile, Gemfile.lock, app/services/hyrax/derivative_service.rb, app/services/oregon_digital/file_set_derivatives_service.rb, config/initializers/hyrax.rb, config/initializers/mini_magick.rb, lib/oregon_digital/derivatives/image/gm_processor.rb, lib/oregon_digital/derivatives/image/gm_runner.rb, lib/oregon_digital/derivatives/image/jp2_processor.rb, lib/oregon_digital/derivatives/image/jp2_runner.rb, lib/oregon_digital/derivatives/image/utils.rb, spec/oregon_digital/derivatives/image/gm_runner_spec.rb, spec/oregon_digital/derivatives/image/jp2_runner_spec.rb, spec/services/oregon_digital/file_set_derivatives_service_spec.rb
Implements derivatives for images in stages.  The openjpeg tools can't
convert many formats to JP2 directly, so we make sure we have a BMP, and
then convert that to JP2.  It's a bit messy and definitely inelegant,
but it does the job.
We also have to implement graphicsmagick-based processing to deal with
the intermediary image conversions.  The Hyrax code uses MiniMagick,
which doesn't work with graphicsmagick when trying to flatten an image,
which Hyrax does on resize operations.  The rationale for ditching
ImageMagick?  ...it doesn't work with huge images.  It just crashes.
The fileset derivative service now subclasses from
Hyrax::FileSetDerivativesService.  This lets us use a single service
without losing the derivative generation Hyrax gives us that we don't
need to customize.
We need …
=> Implement derivative processors

app/indexers/oregon_digital/deep_indexing_service.rb, app/indexers/oregon_digital/metadata_indexer.rb, app/models/concerns/oregon_digital/generic_metadata.rb, app/search_builders/oregon_digital/oembed_search_builder.rb, spec/search_builders/oregon_digital/oembed_search_builder_spec.rb
Fixes #397 by defaulting all metadata to the indexing methods defined in the metadata concerns. eg: https://github.com/OregonDigital/OD2/blob/master/app/models/concerns/oregon_digital/generic_metadata.rb#L22
=> Force index strategy to be defined in metadata concerns

config/initializers/hacks/omniauth_strategies_saml.rb
Fully fixes #173
Removing query_string from the SAML callback URL forces `AssertionConsumerService` in the SAML metadata to always match `AssertionConsumerServiceURL` in the request to the IDP.
=> Remove query string from SAML callback url

lib/oregon_digital/authorities/web_service_redirect.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/spar_media_type.rb
Fixes #391 
The original ticket mentions the issue occurs when the Sparonotolgy endpoint is hit with http. Turns out this breaks our term matching after the redirect limit is raised.
=> Increase QA redirect limit

.circleci/config.yml, Dockerfile
Includes CCI orb for building and pushing docker images to ECR. This depends on some credentials setup in CCI "Environment Variables" for the project, and only builds the image on merges to `master` or a `deploy` branch. The current thinking is that a new image pushed to the ECR repositories that hold these images will trigger a fresh deploy to staging or production environments.
=> uses CircleCI to build and push application images to AWS ECR

app/controllers/catalog_controller.rb
Fixes #463 
We use FAR too much metadata to query via GET.
https://github.com/rsolr/rsolr#using-post-for-search-queries Here's some docs about the underlying Rsolr details.
https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/templates/catalog_controller.rb And the config in Blacklight this changes.
=> Use POST method to query solr

app/authorities/qa/authorities/extended_geonames.rb, app/models/generic.rb
Fixes #392 
There were some left over pieces of code, that were causing a graph to be loaded before fedora.
=> fix location

config/initializers/hacks/hyrax_collections_controller_behavior.rb
Fixes #531 
Facets work similar to catalog controller, but may need to be altered further once we figure out how to display facets on the search page. In particular, https://github.com/samvera/hyrax/blob/master/app/controllers/concerns/hyrax/collections_controller_behavior.rb#L105 may need to include merging a new facets query string
=> Enable facets on collections search

app/controllers/catalog_controller.rb, app/models/concerns/oregon_digital/document_metadata.rb, app/models/concerns/oregon_digital/generic_metadata.rb, app/models/concerns/oregon_digital/image_metadata.rb
Fixes #272 and Fixes #397 
This PR adds a new option to metadata `advance_search` which is recognized in the catalog controller. It also brings the metadata searchability (advanced and simple) and facetability in-line with the MAP (again). The notable exceptions being `date_modified` and `date_uploaded` because that is Core Metadata and un-editable yet. Also and exception, `original_filename` as it is not configured yet.
Not setting `advance_search` will default the metadata's searchability to whether it is indexed as `:stored_searchable` for both advanced and simple search.
Setting `advance_search` to `true` (and indexing as `:stored_searchable`) will only allow the metadata to be searched if the exact field is specified (`&search_field=cover_description&q=<query>`).
Setting …
=> Correct searchability and facetability of metadata

app/views/hyrax/collections/_facets.html.erb, app/views/hyrax/collections/show.html.erb, config/initializers/hacks/hyrax_collections_controller_behavior.rb
Fixes #532.
Display facets exactly as catalog search page does, from Blacklight.
`_facets.html.erb` isn't necessary yet, but will require changes once we can get a list of facets to display for the collection.
Preview of collections search page:
=> Add Blacklight facets to collections search page

app/assets/javascripts/application.js, app/assets/javascripts/oregon_digital/collections/configurable_facets.js, app/assets/stylesheets/oregon_digital/collections/configurable_facets.scss, app/controllers/dashboard/oregon_digital/collections_controller.rb, app/models/collection.rb, app/models/facet.rb, app/views/hyrax/dashboard/collections/_form.html.erb, app/views/hyrax/dashboard/collections/_form_facets.html.erb, config/routes.rb, db/migrate/20190529145822_create_facets.rb, db/schema.rb, spec/controllers/dashboard/oregon_digital/collections_controller_spec.rb, spec/factories/collection.rb, spec/factories/facets.rb, spec/models/collection_spec.rb, spec/models/facet_spec.rb
Fixes #547 
This PR creates a Facet object that is used to store configuration for facets for each collection. It also adds the configurable facet tab to the collections edit form and hooks it up to that facet object. 
Draggable ordering is accessible with tab-focus and (left/up)/(right/down) keyboard navigation.
Preview:
=> Add configurable facets to collections edit form

config/initializers/hyrax_migrator.rb, config/initializers/migrator/crosswalk_admin_sets.yml
This brings over admin set crosswalk file from the migrator to live in OD2 configs with the other .yml files so the service can find it. Modified the id of osu-scarc (see comment on #562)
=> bring over admin_set crosswalk file to OD2

app/indexers/oregon_digital/deep_indexing_service.rb, config/initializers/migrator/crosswalk.yml, config/initializers/migrator/crosswalk_overrides.yml
- Rescue `Net::ReadTimeout` for fetch_value in deep_indexing_service.rb. Occasionally, the fetch raises a timeout (that ends up causing a 500 error related to https://github.com/OregonDigital/OD2/issues/330) that breaks the migrator.
- Updates for crosswalk and crosswalk overrides
=> bugfixes for hyrax-migrator

app/presenters/hyrax/generic_presenter.rb, config/locales/hyrax.en.yml, spec/system/create_audio_spec.rb, spec/system/create_document_spec.rb, spec/system/create_generic_spec.rb, spec/system/create_image_spec.rb, spec/system/create_video_spec.rb
Updates application title to 'Oregon Digital (Development)' largely everywhere. Fixes #594 
Will need to reopen this when we go prod.
Also, work show page is trimmed down to '<work title> | Oregon Digital (Development)' Fixes #602
=> Set page titles

app/views/hyrax/base/_attribute_rows.html.erb, app/views/hyrax/base/_work_title.html.erb, app/views/hyrax/base/show.html.erb, config/initializers/_i18n.rb
Fixes #605 
Fixes #606 
Fixes #608 
- Removes work type heading from work show page
- Changes work title to h1
- Remove citation dropdown from work show page
- Removes work description and sets it as the first attribute row, giving it a label
=> Override show page partial

app/views/hyrax/base/_social_media.html.erb
Fixes #613 
Add a copy to clipboard button
=>  Remove Google+ and Tumblr social links

app/assets/stylesheets/oregon_digital/_files-sets.scss, app/views/hyrax/base/_license.html.erb, app/views/hyrax/base/_print.html.erb, app/views/hyrax/base/show.html.erb, config/locales/hyrax.en.yml
Fixes #612 
Fixes #611 
Fixes #628 
We don't have access to font-awesome v5, so we can't add any of the CC or licensing icons.
=> Adds print and license sections to work show page

app/assets/javascripts/hyrax/search.js, app/assets/stylesheets/oregon_digital/_home-page.scss, app/views/catalog/_search_form.html.erb, config/locales/hyrax.en.yml
Fixes #595 
Public domain is not hooked up for union searching and only returns CC0 works. This will require [blacklight_advanced_search](https://github.com/projectblacklight/blacklight_advanced_search) gem, which I believe we will be tackling later.
Institution searches are filtered on the :institution metadata field, and respond to "University Of Oregon" and "Oregon State University" labels.
unauthed
=> Add UO OSU and PD search scopes

.rubocop_fixme.yml, app/renderers/hyrax/renderers/license_attribute_renderer.rb, app/renderers/hyrax/renderers/rights_statement_attribute_renderer.rb
=> Stop licenses and rights statements from opening in new tabs

app/controllers/catalog_controller.rb, app/presenters/blacklight/rendering/max_values.rb, app/presenters/blacklight/rendering/max_values_label.rb, config/initializers/blacklight.rb
Fixes #687 
- Limit search shown fields
- Break up max_value and max_value_label pipeline steps
- Limit description to 1 value
=> Search List/Gallery view: Metadata field limiting

Gemfile.lock, config/initializers/migrator/crosswalk_admin_sets.yml
update hyrax-migrator to bring changes to admin sets service (logic to fallback to institution field when retrieving admin-set ids and primary_set is not available).
=> update hyrax-migrator to get changes to crosswalk admin sets

app/indexers/generic_indexer.rb, app/models/ability.rb, app/models/user.rb
Fixes #755 
Fixes #756 
This makes sure the solrized groups and the groups the User object returns lines up with what Blacklight expects to restrict discover, read, and access permissions.
=> Apply more groups to Blacklight permissions

build/firstrun.sh
This fixes a problem where the first-run script just crashes because of the missing role
=> First run: make sure the admin role exists

Gemfile.lock, config/initializers/migrator/crosswalk_overrides.yml
- update hyrax-migrator to include patch https://github.com/OregonDigital/hyrax-migrator/pull/151
- override `rights_statement` to point to predicate `http://purl.org/dc/terms/rights` and use new `attributes_replaces_data` to temporarily replace `http://opaquenamespace.org/ns/rights/rr-f` with `http://rightsstatements.org/vocab/InC/1.0/`
=> update migrator and rights_statement to use attributes_replaces_data

build/firstrun.sh
Fixes problem with admin user getting the wrong role now that we
generate roles in the docker entrypoint script
=> Force admin user to have the admin role

app/controllers/concerns/oregon_digital/download_controller_behavior.rb, app/models/ability.rb, app/models/concerns/oregon_digital/ability/work_download_ability.rb, app/views/hyrax/base/_download.html.erb, config/download_restriction.yml, config/routes.rb
Fixes #759 
Fixes #760 
Add a new download_low route to works to be filled in with low res download files later. Setup permissions for download and download_low routes based on matrix
=> Low- and high-res download permissions

app/models/ability.rb, app/models/user.rb, config/roles.yml
Fixes #756 
community_affiliate role does not have any special permissions. A community_affiliate should be affiliated with one or both universities and should have the exact same permissions as a [university]_user role. [university]_affiliate roles takes care of this and slightly simplifies our QA and permissions matrix.
=> Remove community_affiliate role and permissions

Gemfile.lock
update to bring hyrax-migrator security updates: 
https://github.com/OregonDigital/hyrax-migrator/pull/155
https://github.com/OregonDigital/hyrax-migrator/pull/156
https://github.com/OregonDigital/hyrax-migrator/pull/161
=> update hyrax-migrator gem for december 2019 updates

build/firstrun.sh
Fixes initial setup so our admin user is actually usable - at some point we went from just needing an account to needing an account that's got a confirmation date.
=> firstrun.sh: create admin with confirmation timestamp

app/services/oregon_digital/file_set_derivatives_service.rb, spec/services/oregon_digital/file_set_derivatives_service_spec.rb
Fixes our fileset processing service to generate PNGs instead of BMPs
for image derivative intermediate files, which appears to be necessary
for the final conversion from intermediate file to JP2.
It is my believe that this will close #937.  We won't know for certain until we do more testing, but in local dev this worked for all images my system could process (one PDF has 200-megapixel images embedded and my local workstation can't process those)
=> derivatives: use PNGs for intermediate files

lib/oregon_digital/feature_class_uri_to_label.rb, spec/hyrax/controlled_vocabularies/location_spec.rb, spec/oregon_digital/feature_class_uri_to_label_spec.rb
fixes https://github.com/OregonDigital/OD2/issues/943 
This additional fix addresses a mismatch issue when building the label for location. It should display the feature class in parenthesis, i.e. "(Administrative Boundary)".
=> fix FeatureClassUriToLabel to display missing class label

Gemfile.lock
update hyrax-migrator gem to get recent updates:
- Bump rake from 12.3.2 to 13.0.1  dependencies https://github.com/OregonDigital/hyrax-migrator/pull/188 
- Bump puma from 3.12.1 to 4.3.3  dependencies https://github.com/OregonDigital/hyrax-migrator/pull/187 
- Bump nokogiri from 1.10.5 to 1.10.8  dependencies https://github.com/OregonDigital/hyrax-migrator/pull/186 
- implement verify_content method https://github.com/OregonDigital/hyrax-migrator/pull/189
=> update hyrax-migrator gem 3-20-20

app/assets/stylesheets/oregon_digital/_files-sets.scss, app/views/hyrax/base/_items.html.erb, app/views/hyrax/base/_member.html.erb, app/views/hyrax/collections/show.html.erb
Fixes #1024 
Not the prettiest display, but so far it is supposed to be temporary for debugging and working in staging. Madison Avenue and PMOP will decide its fate.
=> Display file sets and child works again

app/controllers/catalog_controller.rb, app/indexers/generic_indexer.rb, config/locales/hyrax.en.yml
This better aligns the search results metadata with #850.
It's not perfect and still needs to display full text. A TODO is added to describe where full text can be put swapped for keyword.
=> Configure search results metadata

app/renderers/search_and_external_link_attribute_renderer.rb
Fixes #1006 
This abstracts and generates combined label searches for the configured fields. Since its only the controlled vocabularies, its only pieces that would search using the _label method.
=> First pass to generalize external link fields

config/initializers/hacks/action_view_javascript_helper.rb
Temporary fix until Hyrax and ActiveFedora (under v3) support rails 5.2 and above.
=> Add monkey patch for CVE-2020-5267

app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb
Being required, the form will not submit if a collection is not provided and prevents a potential Ack! message
Fixes #1150
=> Mark collection required in add to collection modal

app/models/concerns/oregon_digital/work_behavior.rb, spec/models/generic_spec.rb
Something about the ActiveFedora stream wrapper is SLOW. University of Michigan implemented download all as zip functionality very similarly to ours, but accessed the files body directly through fedora with `#open` and `#copy_stream`. They suggest 3G as the maximum zip size and enforce < 10G.
This may fix #1172 
Other options exist with zip_tricks and directly streaming, but this might be fast enough.
=> Speed up download performance by skipping activefedora stream wrapper

config/initializers/hacks/hyrax_collections_controller_behavior.rb, config/initializers/hacks/hyrax_collections_members_controller.rb
Here is an initial proposal to fixing the metadata disappearing after a work is added to a collection. One thing to note here is there is a reindex that happens when a work is added to a collection. this means that metadata (specifically controlled vocabularies) may not be available instantly after a work is added to a collection. 
This has been noted previously when a work is created. But this needs to be extended to "anytime a work is saved" which may not just be on create/update. 
Therefore we have to be mindful of the state of an application after someone adds a work to a collection.
=> Update to add callback to updating a member

app/views/catalog/_document.html.erb, app/views/catalog/_index_gallery_default.html.erb, app/views/catalog/_index_list_default.html.erb
Prevents users from adding collections to user collections as sub-collections.
Nested indexing is still not async and indexes all children works of the collection being added. This can easily cause timeouts.
=> Remove save button and checkboxes from collections

Gemfile.lock
hyrax-migrator updates:
- update: map OD1 workflowMetadata dsCreateDate to OD2 date_uploaded Metadata Migration
https://github.com/OregonDigital/hyrax-migrator/pull/217 by @luisgreg99
- bugfix: failed persisting work pid, javax.jcr.PathNotFoundException: No node exists at path bug
https://github.com/OregonDigital/hyrax-migrator/pull/220 by @luisgreg99
- Bump rack from 2.2.2 to 2.2.3  dependencies
https://github.com/OregonDigital/hyrax-migrator/pull/218 by dependabot bot
=> update hyrax-migrator gem

app/controllers/concerns/oregon_digital/download_controller_behavior.rb, app/models/concerns/oregon_digital/collection_behavior.rb, app/models/concerns/oregon_digital/work_behavior.rb
Fixes downloads not working for non-institutional affiliate users. Work and collection downloads will degrade to low-res downloads once that method is implemented.
=> Stub out low-res download method and control flow

Gemfile.lock, app/indexers/oregon_digital/deep_indexing_service.rb, lib/hyrax/controlled_vocabularies/location.rb, lib/oregon_digital/controlled_vocabularies/resource.rb, lib/oregon_digital/triplestore.rb
So I modified two pieces here. First piece is to allow the triplestore to check to see if it has a term in the cache. This is done using the triplestore adapter's #fetch_from_cache. This method checks the cache and returns nil if it isnt in the cache. 
Next I modified the AT::Resources to allow them to check to see if their rdf_subject is in the cache. It returns a boolean depending on if it is in the cache.
Lastly, I updated the BLOCKING portion of the indexing, which is the #fetch_value portion of the deep_indexing_service. Now, what it does is iterates through all the CVs that were pushed through the form. It calls the #fetch_with_persistence method when the term is verified that it is in the triplestore. This will call fetch on the term, return quickly, and index the data. 
This is to …
=> checks cache during blocking and indexes if in cache

Dockerfile
For some reason when Rails runs `yarn install` it doesn't install `shx` which is dependency of `uv`'s after-install scripts.
If we run yarn install before Rails does, `shx` will exist.
Fixes #1262
=> Run yarn install before rails runs yarn install

app/views/oregon_digital/explore_collections/_showcase_tile.html.erb
Fixes #1244 
Chose `items` over `total items` because the latter very often introduces line breaks between `total` and `items`.
=> Add 'items' to item count parenthetical

config/initializers/hacks/hyrax_collections_controller.rb
This ups the efficiency of the saves for batches by chunking the array of batches into smaller groups.
The math behind this goes as such: 10! is an extremely large number. but if we do 2 groups of 5! then its a much smaller more manageable number. 
10! = 3628800
5! + 5! = 240
So if we split the batch up into smaller groups, then it should increase the save speed immensely.
=> chunk out batch to increase efficiency of save

app/models/concerns/oregon_digital/generic_metadata.rb, config/initializers/migrator/crosswalk.yml, config/initializers/migrator/crosswalk_overrides.yml
Fixes #1418 
Update barcode predicate and the migrator crosswalk, and then add the override to flip it from the current OD1 predicate.
=> Update barcode predicate, including crosswalk, add override.

app/assets/stylesheets/oregon_digital/_breadcrumbs.scss, app/controllers/catalog_controller.rb, config/initializers/hacks/hyrax_bootstrap_breadcrumbs_builder.rb
Last of the desktop view work for #1376 and some for #1377 
- Removes an init hack that has been fixed upstream related to breadcrumbs (a11y)
- Adds a breadcrumb linked to home to the search results
- CSS for breadcrumb
=> Breadcrumbs for search view

app/assets/stylesheets/oregon_digital/_buttons.scss, app/assets/stylesheets/oregon_digital/_search.scss, app/assets/stylesheets/oregon_digital/_work-show.scss, app/assets/stylesheets/oregon_digital/utils.scss, app/views/catalog/_index_header_list_collection.html.erb, app/views/catalog/_index_header_list_default.html.erb, app/views/catalog/_index_list_default.html.erb, app/views/catalog/_per_page_widget.html.erb, app/views/catalog/_sort_and_per_page.html.erb, app/views/catalog/_sort_widget.html.erb, app/views/catalog/_thumbnail_list_collection.html.erb, app/views/catalog/_thumbnail_list_default.html.erb, app/views/hyrax/base/_metadata.html.erb, app/views/hyrax/base/show.html.erb, config/locales/blacklight.en.yml
Fixes #1376 
iPhone X/XS:
iPad:
1080p:
Does work to separate some CSS from work show page and search results.
Then reconciles mobile and desktop views for list view of search results.
=> Mobile layout and tweaks for search results (list)

app/views/catalog/_metadata_masonry_default.html.erb
=> Add metadata and compound object information to masonry search results

app/assets/stylesheets/oregon_digital/_work-show.scss, app/views/hyrax/base/_show_actions.html.erb, app/views/hyrax/base/_work_title.html.erb
Fixes #1471 
Turns the work actions into a flexbox instead of BS grid. Also moves the second row of actions (admin actions) inline with regular actions, keeping the editor/admin checks
=> Add print button and move copyright on work show page

app/models/blacklight_iiif_search/iiif_search.rb, app/presenters/oregon_digital/iiif_presenter.rb, config/initializers/hacks/iiif_manifest_canvas_builder.rb
Fixes #1110 
This includes the gsub fix but also two new bugfixes.
- Parent works were not properly setting the id for child canvases. This was fixed by making sure that child work presenters are properly set to our custom IIIFPresenter class, not Hyrax's WorkPresenter class (`iiif_presenter.rb`)
- Only the parent work id was joined against file sets to find OCRd/scraped text. This was fixed by including all member ids into the solr fq join statement. (`iiif_search.rb`)
=> IIIF Manifest fixes for compound objects

app/services/oregon_digital/listeners/metadata_fetch_listener.rb
This is needed because of multiple worker nodes. If the FetchGraphWorker starts before AttachFilesToWork we can end up overwriting the work of the FetchGraphWorker. This change enqueues another FGW after AttachFilesToWork finishes.
Fixes #1432
=> Fire off FetchGraphWorker after attaching fileset to work on ingest

app/search_builders/oregon_digital/in_review_search_builder.rb, spec/search_builders/oregon_digital/in_review_search_builder_spec.rb
Fixes #1460 
The old search builder would get confused when the Solr index was out-of-sync with Sipity entities in Postgres. Sipity entities seem to be more likely to get out-of-sync, probably because they're not very relevant to search.
The new way uses the Hyrax method to get all the correct Solr documents then pipes those IDs into the search builder. This will work much more often, but it will query all three datasources several times (Postgres, Fedora, Solr)
=> Get IDs for the review queue the Hyrax way

app/controllers/users/confirmations_controller.rb, config/routes.rb
Fixes #1540 
This causes a user to login after they visit the confirmation link they are sent. This is technically a security risk, but accounts are not really tied to very sensitive information, maybe just email address.
Adapted from this SO: https://stackoverflow.com/questions/18655334/avoid-sign-in-after-confirmation-link-click-using-devise-gem
=> Log user in after visiting confirmation link

.circleci/config.yml
According to [this yarn issue](https://github.com/yarnpkg/yarn/issues/8389) updating the CCI version of docker will fix this error:
```
error An unexpected error occurred: "EPERM: operation not permitted, copyfile '/data/.cache/yarn/v6/npm-form-data-2.3.3-dcce52c05f644f298c6a7ab936bd724ceffbf3a6-integrity/node_modules/form-data/License' -> '/data/node_modules/form-data/License'".
```
while building on CCI
=> Set CCI remote docker version to 20.10.2

app/models/solr_document.rb, app/search_builders/oregon_digital/parents_search_builder.rb, spec/search_builders/oregon_digital/parents_search_builder_spec.rb
Removes one ActiveFedora look up, that may happen many times in search
Attempts to fix #1742
=> Look for solr document parents based on the ID from the current solr document

app/views/hyrax/collections/show.html.erb, config/initializers/hacks/hyrax_collections_controller_behavior.rb
Convert `institution_image_path` to `institution_image_info` which returns alt text, image height, and image path
Fixes #1830
=> Add relevant alt text to collection institution image

app/views/hyrax/collections/_showcase_tile.html.erb
Added aria-label to collection landing images to ensure that links had discernible text when titles are hidden
=> Ticket #1747: Collection Landing: Link Names for Images

app/assets/javascripts/blacklight/ajax_modal.js, app/assets/stylesheets/oregon_digital/_facets.scss, app/assets/stylesheets/oregon_digital/bootstrap/_modals.scss, app/views/catalog/_facet_layout.html.erb, app/views/catalog/_facet_limit.html.erb, app/views/catalog/facet.html.erb, app/views/layouts/hyrax.html.erb, app/views/shared/_ajax_modal.html.erb
Fixes #1840
Moving the modal above the footer is just good practice (footer should be last-ish) and prevents the modal from tabbing into the browser interface
Modals should open from buttons, not links
When closing the modal, focus jumps back to the opening element
Move button after modal title to get screen readers to announce the modal title
=> Bootstrap modal improvements

app/assets/stylesheets/_variables.scss, app/assets/stylesheets/oregon_digital/_search.scss, app/assets/stylesheets/oregon_digital/explore_collections/_buttons.scss
Fixes #1885
Fixes #1788 
#1788 mentions POSM's decision to change the orange we use in cases like this. I added a new `$contrast-orange` to use with `$navy-blue`
When we're all done with a11y tickets, we need to go and audit various links and mouse-over cursors, to make sure enough is changing on hover & on focus to meet a11y standards.
=> White text on orange background contrast improvements

app/views/hyrax/homepage/_login_modal.html.erb
Fixes #1338
Adds more accurate description of purpose of the images rather than the image itself.
=> update alt text to describe purpose and not image

app/controllers/oregon_digital/explore_collections_controller.rb, app/models/concerns/oregon_digital/ability/work_show_ability.rb, app/views/oregon_digital/explore_collections/_index_table.html.erb
Fixes #1487 
This changes the code to grab an active fedora item and do the ability check on that. If we don't do this, then what is returned is a `SolrHit` which is something we are not doing checks for. It gets transformed into an AF::Base object and then checked for compatibility.
=> Update rules for users to see locks

app/controllers/oregon_digital/explore_collections_controller.rb, app/views/layouts/hyrax.html.erb
Fixes #1896 
This allows controllers and presenters to set the page title with the method `#page_title` as seen in the explore collections controller
=> Allow controllers and presenters to control the page title

Dockerfile
Old URL is dead, so this is a necessary fix to get the image to build
=> Update ImageMagick URL

app/views/hyrax/base/_work_contact_form.html.erb, app/views/hyrax/contact_form/new.html.erb
Fixes #2024 
Note: This only works on browsers that support the new HTML 5 values for `autocomplete`. At time of writing that is Chrome & Opera. This is not a breaking attribute for other browsers and they should implement this standard over time.
Because this is "new" it is not supported by Firefox or Safari yet.
=> Use autocomplete attribute on contact forms

app/assets/javascripts/hyrax/search.js, app/views/catalog/_constraints.html.erb
(fixes #1908  )
@CGillen confirmed that the title issue had been previously fixed. 
I chose to automatically place the focus on the view type group because that seemed like the first piece of search content. Let me know if I need to place the focus on a different element or if you want the <script> in a separate file.
=> Ticket #1908: Commit to set focus to search content

app/views/_masthead.html.erb
fixes #1791 
Breadcrumb aria-label had been previously fixed
=> Ticket #1791: Commit to delete masthead aria-label

app/workers/fetch_graph_worker.rb, lib/oregon_digital/controlled_vocabularies/resource.rb, lib/oregon_digital/controlled_vocabularies/scientific.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/itis.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/ubio.rb, spec/oregon_digital/controlled_vocabularies/scientific_spec.rb
fixes #2128
fixes #2153
Automatically calling the FetchFailedGraphWorker when the connection fails for itis and ubio fetching could be a mess, but hopefully not once we're checking the triplestore before fetching.
=> Handle errors

Dockerfile, app/workers/fetch_failed_graph_worker.rb, app/workers/fetch_graph_worker.rb, app/workers/reindex_worker.rb, build/entrypoint-tools.sh, config/initializers/_hyrax.rb, config/initializers/sidekiq.rb, config/sidekiq.yml, lib/tasks/oregon_digital/reindex_all.rake
- Sets the ingest queue name config global that Hyrax uses for "ingest related" jobs to `:ingest`
- Sets graph jobs to `:graph`
- Sets reindex job to `:reindex`
- commented framework in config/initializers/sidekiq.rb for setting queue names for individual job types
- removed a few junk files from /data in the Dockerfile
- updates `build/entrypoint-tools.sh` script to exec `/sbin/init` instead of using a `while ... sleep` loop
- Add these queues to Sidekiq:
- `:ingest`
- `:reindex`
- `:graph`
- `:notify`
=> [Ready] specify queues for graph/reindex sidekiq jobs

app/indexers/oregon_digital/deep_indexing_service.rb, app/workers/fetch_failed_graph_worker.rb, app/workers/fetch_graph_worker.rb, spec/indexers/oregon_digital/deep_indexing_service_spec.rb, spec/workers/fetch_failed_graph_worker_spec.rb, spec/workers/fetch_graph_worker_spec.rb
fixes #2287 
This branch includes the following:
1. moves the indexing of combined labels and location label from FetchGraphWorker and stashes it all in the DeepIndexingService
2. similarly, removes indexing from FetchFailedGraphWorker.
3. overrides add_assertions in DIS to index the combined labels and prevents unfetched labels from being indexed
4. overrides fetch_external to block it from running if the asset has not passed a certain point in the workflow; at the moment the test is object.representative_id, which is assigned when the AttachFilesJob runs. After that, all indexing jobs will also index the labels for controlled fields. Potentially we could delay it even further, but this seems like a fair compromise: the asset has finished its initial creation but we are not waiting for …
=> Move combined labels

app/models/concerns/oregon_digital/ability/work_show_ability.rb
Revert `:read` permission for unauthed manifest generation
Fixes #1423 #1450 #1386
=> Revert :read permissions for work show

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb, app/indexers/generic_indexer.rb, app/indexers/oregon_digital/file_set_indexer.rb, app/models/file_set.rb, app/services/oregon_digital/hocr_derivative_service.rb, config/locales/hyrax.en.yml
Fixes #1450 
FileSets and Works have new solr `hocr_text_tsimv` and add that field to blacklight searching/search results (description, full text, hocr text hit highlighting)
=> Separate extracted and ocr text for searching

Gemfile.lock, config/initializers/migrator/crosswalk_admin_sets.yml
get fixes for migrator label verifier, full_size_download_allowed, also makes changes to the crosswalk admin set config file wrt full_size_download_allowed
=> migrator update 90ae9c5

Gemfile.lock
fix rubocop inflicted wound to full_size_download_allowed method in the migrator crosswalk service
=> Migrator update 9e07bb9

app/models/collection.rb, spec/models/collection_spec.rb
As an afterthought, copying Hyrax::CollectionNesting methods for reindex_extent, to allow reindex_extent to behave the way hyrax expects it to, ie settable, eg in the case where the config is set to 'full', a full reindex is not necessary, and the request is coming from the dashboard.
followup to #2387
=> let reindex_extent be settable

app/models/concerns/oregon_digital/document_metadata.rb
Restore earlier value, match the MAP
Fixes #2411
=> Fix has_number predicate

lib/hyrax/controlled_vocabularies/location.rb, spec/hyrax/controlled_vocabularies/location_spec.rb, spec/indexers/oregon_digital/deep_indexing_service_spec.rb, spec/workers/fetch_graph_worker_spec.rb
Fixes #2452 
The issue with the label being wrong is an issue with the cache. This implements a fix for the case where a city may be in multiple counties:
`Salem >> Marion/Polk Counties >> Oregon >> United States`
=> Handle case where location may be in multiple counties

Gemfile, Gemfile.lock
I had left this gem out thinking it was optional and we didn't need it, but at least one of the jobs is expecting it. I think I saw newer versions of bulkrax remove the gem as a requirement.
=> Add willow sword gem for bulkrax.

app/controllers/concerns/hyrax/dashboard_authorization.rb, config/initializers/hacks/hyrax_dashboard_authorization.rb
@CGillen Wanna check this out? This is the fix i found for the logged in users not being able to generate collections. The controllers were blocking the access through rails stuff and bypassing our cancan permissions. The other idea would be to figure out how to refine the DashboardAuthorization to be able to check if they are trying to create a collection or create a new authorization. Im not sure we need it though.
Thoughts?
=> comment out possible unnecessary perms

app/workers/reindex_one_lite.rb
This simplifies the ReindexWorker, for existing works that just need metadata and indexing refreshed. With the 'reindex' queue specified, larger reindex jobs can be spread out across workers as needed.
=> Add ReindexOneLite worker.

app/services/oregon_digital/file_set_derivatives_service.rb, spec/services/oregon_digital/file_set_derivatives_service_spec.rb
Fixes #1425
Trims border pixels, usually white padding but will be all border pixels that exactly match pixel [0, 0]
=> Apply imagemagick trim to pdf derivatives

app/presenters/oregon_digital/iiif_presenter.rb
=> sorts in UV for index list

app/views/hyrax/base/_index_gallery.html.erb
fixes #2861 
Before bug fix:
After bug fix:
=> Fix non html safe rendering of encoded titles in Part Of view

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
Add in the `cultural context` facet to the OD2 search filter for users.
=> Add in cultural facet

app/controllers/concerns/oregon_digital/download_controller_behavior.rb
Fixes #1942 
Downloading zip with title length greater than 5:
Downloading csv with title length greater than 5:
Downloading zip with title length less than 5:
=> Set file naming schema for downloads: <5_word_title>_<pid>.<extension>

app/assets/stylesheets/oregon_digital/collections/show.scss
Remove the `font-style: italic` part in the `.hyc-desc` to fit with the `a11y` standard.
=> Remove italicize for collection section

app/views/hyrax/base/_citation_and_copy_button.html.erb
Fixes #1718  
New position of copy buttons:
=> Update copy button position

app/views/hyrax/homepage/_home_content.html.erb
Add in the hyperlink to the title of the `feature collection` page on the homepage layout.
=> Add in link to feature collection

app/jobs/bulkrax/exporter_job.rb
fixes #2934 
I was going to add the same code to the importer job, but that doesn't really stick around the same way the exporter job does.
=> make export jobs cancellable

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb, app/views/catalog/_facet_index_navigation.html.erb, app/views/catalog/facet.html.erb
Rough working implementation of an A-Z index filter (closes #1133 ) in the Filters > Topic > More modal.
Default "All Topics":
Topics filtered by letter:
Topics filtered by letter (case: no topics):
Accessibility work that’s happened so far:
- A-Z Links are each list items so that screen reader users know how long the list is + make an informed decision.
- Wrapped a nav tag around the list with an aria-label for easier navigation and clarity of purpose.
- Added a heading after the navigation for a screen reader user to skip to. 
- Designated the heading as an aria-live region that screen readers will read after a live update. Only the heading is read to prevent an uninterrupted, not-useful reading of every topic on screen. 
Needs feedback/more work:
- Content of live heading. Currently …
=> AZ Topic facet filter

app/views/catalog/_search_results.html.erb, app/views/hyrax/admin/workflows/_sort_and_per_page.html.erb, app/views/hyrax/admin/workflows/index.html.erb
Fixes #1744 
if workflows controller, don't include second sort_and_per_page partial
adjust column widths for search and save widgets to usually have both on 1 line
add button class to action button to match catalog controller
set page title to Review Submissions
remove extra 'content' div that was constraining width, adjust Filters and content column widths
=> Review queue width tweaks and cleanup.

app/views/catalog/_facet_index_navigation.html.erb
fixes #3023 
Topic facet before clicking a letter in the menu (within a topic):
Topic facet after clicking a letter in the menu (within a topic):
Topic facet after clicking a letter in the menu (all topics):
=> Update AZ facet filters to correct search state

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb, app/indexers/generic_indexer.rb
`UPDATE:` Fix some of the `indexers` and `catalog search` field based on the Solr meeting.
`TASK PROGRESS`
=> Update minor to the indexer and catalog

app/inputs/label_and_uri_controlled_vocabulary_input.rb, app/models/solr_document.rb
`UPDATE PART: 2` Add in the helper method to parse out and display on form correctly if `uris` are deprecated.
`TASK PROGRESS:`
=> Add in label parser method to help display

app/services/oregon_digital/verify_derivatives_service.rb, config/environments/development.rb, config/environments/production.rb, spec/services/oregon_digital/verify_derivatives_service_spec.rb
=> Verify derivs

app/controllers/concerns/oregon_digital/presents_data_sources.rb, app/models/concerns/oregon_digital/metadata_download.rb, app/views/hyrax/base/_attribute_rows.html.erb, app/views/hyrax/base/_data_sources.html.erb, spec/models/collection_spec.rb, spec/models/generic_spec.rb, spec/services/oregon_digital/collection_streamer_spec.rb, spec/services/oregon_digital/file_set_streamer_spec.rb
`UPDATE:` Continue to update more on the display usage of the new `label$uri`
`TASKS:` To-Do lists
=> Cleanup on Display labels & uris

app/views/hyrax/base/_currently_shared.html.erb
Fixes #3062
Me and Ryan met about this ticket. Its more work than worth to actually clean up the data. However, we added some data to help explain why there are duplicate name/rows and what the permission for those dups are. We also disabled the dropdown because the permissions don't make sense changing access level when we are expressing permissions differently.
=> Disables dropdown and adds text to make data more clear

app/services/oregon_digital/file_set_derivatives_service.rb
fixes #2489 
Screenshot with corrected colors:
Screenshot before fix:
=> Fix dark image derivatives in Universal Viewer

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb, app/indexers/oregon_digital/file_set_indexer.rb, app/models/file_set.rb, app/services/oregon_digital/file_set_derivatives_service.rb, app/workers/re_extract_text_worker.rb
=> Skip creating bbox file if extracted text is empty & reset bbox on recreate

app/services/oregon_digital/file_set_derivatives_service.rb, app/services/oregon_digital/verify_derivatives_service.rb, app/workers/re_extract_text_worker.rb, lib/oregon_digital/derivatives/document/pdf_to_text_processor.rb
Bad extracted text return was preventing Tesseract from running on PDFs that needed OCR
=> Skip saving BBOX if solr/tika returned bad extracted text

app/assets/stylesheets/oregon_digital/_work-show.scss, app/forms/oregon_digital/forms/collection_form.rb, app/models/concerns/oregon_digital/collection_metadata.rb, app/views/hyrax/collections/show.html.erb, spec/forms/oregon_digital/forms/collection_form_spec.rb
`FEATURE:` Add in the `Collection` content masking on the front-end and test on the message display.
`TO-DO:`
=> Add in Content Mask for Collection

app/indexers/concerns/oregon_digital/parsable_label_behavior.rb, app/indexers/generic_indexer.rb, app/indexers/oregon_digital/collection_indexer.rb
=> add parsable label to colls

app/controllers/concerns/oregon_digital/aspace_digital_object_export_behavior.rb, spec/system/create_audio_spec.rb, spec/system/create_document_spec.rb, spec/system/create_generic_spec.rb, spec/system/create_image_spec.rb, spec/system/create_video_spec.rb
=> method call typo

app/controllers/oregon_digital/explore_collections_controller.rb, config/locales/hyrax.en.yml, spec/controllers/oregon_digital/explore_collections_controller_spec.rb
`FEATURE:` Update the `breadcrumbs` and `page title` to be unison with each other to keep the consistency the same. Edit/modify is done for the `Explore Collections`.
=> Update the display of collection breadcrumbs

app/models/solr_document.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, spec/models/solr_document_spec.rb
fixes #3127 
behavior is only triggered when a COUS (compound of unusual size) is included in the search results, 
RSolr::Error::Http - 414 Request-URI Too Long
=> Solr doc children fix

app/authorities/qa/authorities/publisher.rb, app/authorities/qa/authorities/subject.rb
fixes #2996 
Updates subject and publisher fields so that Wikidata URIs save to a resource and the appropriate labels show up on the work. The URIs already saved for the creators and scientifics fields.
Screenshots of various Wikidata URIs successfully saving to the subject and publisher fields:
Additional screenshots of the URIs saving to a creator and scientific field:
=> Fix wikidata URI json id for subject and publisher fields

app/views/oregon_digital/oembeds/_table.html.erb, app/views/oregon_digital/oembeds/_table_headers.html.erb, app/views/oregon_digital/oembeds/index.html.erb, config/locales/oregon_digital.en.yml
Fixes #3153 
The lookup for the parent work on each FileSet was causing the full object to load, which doesn't scale with hundreds of entries. Further, after recent updates for Valkyrie, the value returned was only ever `Work`. I opted to remove this entirely for now, to speed up page loads.
Also moved the Edit link out, made it explicit, where the link on title goes to the FileSet. Last Modified may help for future debugging, or it could also be changed to Depositor. Added page title on the index page, and cleaned up a few labels to be more consistent.
=> Remove curation_concern lookup, other edits.

app/views/hyrax/file_sets/_form.html.erb
Closes #3177 
Screenshots:
Edit form for oembed file:
Edit form for non-oembed file:
=> Add oembed url field in edit oembed file form

lib/hyrax/controlled_vocabularies/location.rb, lib/oregon_digital/controlled_vocabularies/resource.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/spar_media_type.rb, spec/hyrax/controlled_vocabularies/location_spec.rb, spec/oregon_digital/controlled_vocabularies/institution_spec.rb, spec/oregon_digital/controlled_vocabularies/resource_spec.rb
Reverts OregonDigital/OD2#3056
Reverting this for now, since there's still problems with #1342.
We'll revisit next workcycle, but need to be sure this works reliably for new works, existing works, and via the form, console, and bulkrax.
=> Revert "Solrize CVs with consistant https scheme"

app/services/oregon_digital/institution_picker.rb, spec/services/oregon_digital/institution_picker_spec.rb
Reverts OregonDigital/OD2#3193
Changing back until more of the http/https changes can get in, for #1342. Without those, there's no label for the Institutions fetched if Institution URIs are changed to `https`
=> Revert "Update institution_picker.rb"

app/search_builders/oregon_digital/only_osu_collections_behavior.rb, app/search_builders/oregon_digital/only_uo_collections_behavior.rb
Reverts OregonDigital/OD2#3194
Changing back until more of the http/https changes can get in, for #1342. Without those, there's no label for the Institutions fetched if Institution URIs are changed to `https`
=> Revert "Update only institution behavior"

.rubocop.yml, app/jobs/bulkrax/export_work_job.rb
=> Fix exporter status

lib/oregon_digital/controlled_vocabularies/vocabularies/getty_aat.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/getty_tgn.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/getty_ulan.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/loc_ethnographic_terms.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/loc_genre_forms.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/loc_graphic_materials.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/loc_names.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/loc_orgs.rb, lib/oregon_digital/controlled_vocabularies/vocabularies/loc_subjects.rb
fixes #3238 
block uris using https for LOC and Getty. Attempting to create a new vocab with one will result in  OregonDigital::ContolledVocabularies::ControlledVocabularyError: Term not in controlled vocabulary.
=> Block https loc

app/assets/stylesheets/oregon_digital/_footer.scss
Closes #3215 
- Updates site footer responsive breakpoints and behavior to match prod
- Reduces padding between links
- Fits left border to content
=> Site Footer bootstrap upgrade

.circleci/config.yml, app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb, app/indexers/generic_indexer.rb
`BUGS:` Fix a bug in sorting label for `collection` by adding in a new field to Solr and then implement this field in the blacklight `facet`. Need reindex as well.
fixes #3233
=> Add in a new facet solr field for Collection

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb, app/helpers/oregon_digital/hyrax_helper_behavior.rb
`BUG:` Remove the `helper_method` causing it to not display on the facet search page. Add in a function to parse out the weird bracket in the label.
fixes #3187
=> Remove method causing display Failure
