.gitignore
config/application.rb
config/local_env.example.yml

this gives the ability to store local_env.yml in a protected location, and then inject those values into the application on boot.

adds local_env for protected ENV variables

---

.env
docker-compose.yml

bring docker-compose in line with typical development environment

sets docker-compose for developer work

---

config/application.rb
lib/oregon_digital.rb
lib/oregon_digital/version.rb
lib/tasks/oregon_digital/version.rake

adds application version to OD2 for use by system and deployment

---

Gemfile
Gemfile.lock
app/forms/hyrax/generic_form.rb
app/models/generic.rb
app/models/solr_document.rb
app/presenters/hyrax/generic_presenter.rb
app/renderers/oembed_attribute_renderer.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/records/edit_fields/_default.html.erb
config/initializers/oembed_providers.rb
config/locales/hyrax.en.yml
spec/renderers/oembed_attribute_renderer_spec.rb

Initial configuration of oEmbed

---

config/blazegraph/RWStore.properties
docker-compose.override.yml-example
docker-compose.yml

adds blazegraph to docker

---

.gitignore
config/initializers/hyrax.rb

configures shared storage locations to work with deployed and local dev

---

.dockerignore
Dockerfile

adds the missing application code to the docker image for deployment and ignores local overrides and artifacts

adds application code to docker image, ignores local artifacts

---

app/models/ability.rb

Add ability for admins to manage roles.

---

app/views/shared/_footer.html.erb
spec/oregon_digital/version_spec.rb
spec/rails_helper.rb
spec/views/shared/_footer.html.erb_spec.rb

adds deployed version to footer

---

app/forms/hyrax/image_form.rb
app/models/concerns/oregon_digital/image_metadata.rb
app/models/image.rb
app/models/solr_document.rb
app/presenters/hyrax/image_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
config/locales/image.en.yml
spec/forms/hyrax/image_form_spec.rb

added custom metadata for image work type

---

app/forms/hyrax/image_form.rb
app/forms/oregon_digital/image_form_behavior.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/models/concerns/oregon_digital/image_metadata.rb
app/presenters/hyrax/image_presenter.rb
spec/system/create_image_spec.rb

Add generic terms in image form and presenter
references #146

Include generic terms in image form and presenter

---

build/validate_migrated.sh

fixes bash script bug

---

app/controllers/application_controller.rb

purge problematic plaintext posting of peoples passwords

---

app/controllers/hyrax/generics_controller.rb
app/controllers/oregon_digital/oembeds_controller.rb
app/helpers/oregon_digital/oembed_helper.rb
app/models/generic.rb
app/models/oembed_error.rb
app/presenters/oregon_digital/oembed_presenter.rb
app/renderers/oembed_attribute_renderer.rb
app/search_builders/oregon_digital/errored_oembed_search_builder.rb
app/services/oregon_digital/oembed_service.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/oregon_digital/base/_form_oembed_url.html.erb
app/views/oregon_digital/oembeds/_list_errored_oembeds.html.erb
app/views/oregon_digital/oembeds/_list_oembeds.html.erb
app/views/oregon_digital/oembeds/_oembed_list_errors.html.erb
app/views/oregon_digital/oembeds/edit.html.erb
app/views/oregon_digital/oembeds/index.html.erb
config/locales/oregon_digital.en.yml
config/routes.rb
db/migrate/20181203183652_create_oembed_errors.rb
db/schema.rb
spec/controllers/oregon_digital/oembeds_controller_spec.rb
spec/factories/oembed_errors.rb
spec/models/oembed_error_spec.rb
spec/renderers/oembed_attribute_renderer_spec.rb
spec/search_builders/oregon_digital/errored_oembed_search_builder_spec.rb

Fixes #169
oEmbed Status column working:
Error view:
Error resolution form:

Errors view for oEmbed dashboard

---

app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/services/oregon_digital/user_attribute_service.rb
spec/services/oregon_digital/user_attribute_service_spec.rb

Fixes #184 This should redirect for any oregonstate.edu email. Does not support orst.

Setup redirect in user service for all emails

---

app/models/concerns/oregon_digital/generic_metadata.rb

In this context facetable is `sim` stored indexed multivalued
Fixes #210

update metadata per map changes

---

app/controllers/application_controller.rb

doesnt route to login page

---

config/blazegraph/RWStore.properties
docker-compose.yml

Fixes #281 
Tests still don't pass for me locally, but that appears to be a separate issue.

Move blazegraph data volume

---

config/authorities/resource_types.yml
config/schema_org.yml

resource type updated

---

config/initializers/devise.rb
docker-compose.yml

Fixes code related issues of #173 
The rest is environment setup based on the env vars grabbed here

Grab UO SAML config from env

---

config/initializers/devise.rb
docker-compose.yml

Fixes some mistakes in PR #295

Fix grabbing UO SAML config from env

---

.rubocop_fixme.yml
Gemfile
Gemfile.lock
app/controllers/concerns/hyrax/contact_form_recaptcha_behavior.rb
app/controllers/hyrax/contact_form_controller.rb
app/views/hyrax/contact_form/new.html.erb
config/initializers/config_hack.rb
config/initializers/hyrax.rb
config/initializers/recaptcha.rb
docker-compose.yml
spec/controllers/hyrax/contact_form_controller_spec.rb

Adds in recaptcha

---

app/authorities/qa/authorities/tgn.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/views/records/edit_fields/_tgn.html.erb
lib/oregon_digital/controlled_vocabularies/historic_place.rb
spec/authorities/qa/authorities/tgn_spec.rb
spec/oregon_digital/controlled_vocabularies/historic_place_spec.rb

Add TGN as a controlled field

---

app/models/concerns/oregon_digital/generic_metadata.rb

Change owner to multi-valued to match MAP

---

docker-compose.yml

Fixes #344 and removes test persistence of solr indices

Fix solr volumes

---

README.md
build/firstrun.sh

Makes for a slightly more streamlined process when you need to start fresh

Add firstrun.sh and instructions

---

app/controllers/catalog_controller.rb

Intended to fix #272. Also gets searchable fields up-to-date with the MAP
@straleyb Is there more to #272 that this does not cover?

Enable searching for labels

---

config/initializers/sidekiq.rb
config/routes.rb
docker-compose.yml

adds sidekiq admin UI

---

lib/oregon_digital.rb
lib/oregon_digital/derivatives.rb
lib/oregon_digital/derivatives/image.rb

Closes #145 
Using `RAILS_ENV=staging`, this seems to fix the namespace problem described in the ticket's last comments

Add namespace-magicky files

---

app/authorities/qa/authorities/base_authority.rb
app/authorities/qa/authorities/ethnographic_term.rb
app/authorities/qa/authorities/format.rb
app/authorities/qa/authorities/local_collection_name.rb
app/authorities/qa/authorities/repository.rb
app/authorities/qa/authorities/tgn.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/views/records/edit_fields/_repository.html.erb
lib/oregon_digital/controlled_vocabularies/repository.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/loc_names.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_repository.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ulan.rb
spec/authorities/qa/authorities/ethnographic_term_spec.rb
spec/authorities/qa/authorities/format_spec.rb
spec/authorities/qa/authorities/local_collection_name_spec.rb
spec/authorities/qa/authorities/repository_spec.rb
spec/authorities/qa/authorities/tgn_spec.rb
spec/oregon_digital/controlled_vocabularies/repository_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/loc_names_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/ons_repository_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/ulan_spec.rb

Working on parsing http://vocab.getty.edu/ulan/500302766.json which returns some really terribly formatted json response. Then we have two other vocabs to go over for this one and that should complete it.

set up initial framework for repository

---

app/authorities/qa/authorities/base_authority.rb
app/authorities/qa/authorities/ethnographic_term.rb
app/authorities/qa/authorities/format.rb
app/authorities/qa/authorities/local_collection_name.rb
app/authorities/qa/authorities/repository.rb
app/authorities/qa/authorities/tgn.rb
lib/oregon_digital/controlled_vocabularies/ethnographic_term.rb
lib/oregon_digital/controlled_vocabularies/historic_place.rb
lib/oregon_digital/controlled_vocabularies/local_collection_name.rb
lib/oregon_digital/controlled_vocabularies/media_type.rb
lib/oregon_digital/controlled_vocabularies/repository.rb
lib/oregon_digital/controlled_vocabularies/resource.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/getty_tgn.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/loc_ethnographic_terms.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_local_collection_name.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/spar_media_type.rb
spec/authorities/qa/authorities/ethnographic_term_spec.rb
spec/authorities/qa/authorities/format_spec.rb
spec/authorities/qa/authorities/local_collection_name_spec.rb
spec/authorities/qa/authorities/tgn_spec.rb

Refactor existing single endpoint controlled vocabularies

---

app/authorities/qa/authorities/culture.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/views/records/edit_fields/_cultural_context.html.erb
lib/oregon_digital/controlled_vocabularies/culture.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/getty_aat.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/loc_subjects.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_culture.rb
spec/authorities/qa/authorities/culture_spec.rb
spec/oregon_digital/controlled_vocabularies/culture_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/getty_aat_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/loc_subjects_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/ons_culture_spec.rb

Add Culture controlled vocabulary

---

app/authorities/qa/authorities/style_period.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/views/records/edit_fields/_style_or_period.html.erb
lib/oregon_digital/controlled_vocabularies/style_period.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_style_period.rb
spec/authorities/qa/authorities/style_period_spec.rb
spec/oregon_digital/controlled_vocabularies/style_period_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/ons_style_period_spec.rb

Add Style Period controlled vocabulary

---

app/authorities/qa/authorities/form_of_work.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/views/records/edit_fields/_form_of_work.erb
lib/oregon_digital/controlled_vocabularies/form_of_work.rb
spec/authorities/qa/authorities/form_of_work_spec.rb
spec/oregon_digital/controlled_vocabularies/form_of_work_spec.rb

Add Form of Work controlled vocabulary

---

.rubocop_fixme.yml
app/authorities/qa/authorities/subject.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/views/records/edit_fields/_military_branch.html.erb
app/views/records/edit_fields/_subject.html.erb
lib/oregon_digital/controlled_vocabularies/subject.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/loc_genre_forms.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/loc_graphic_materials.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/loc_orgs.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_osu_buildings.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_subject.rb
spec/authorities/qa/authorities/subject_spec.rb
spec/oregon_digital/controlled_vocabularies/subject_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/loc_genre_forms_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/loc_graphic_materials_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/loc_orgs_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/ons_osu_buildings_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/ons_subject_spec.rb

Add Subject controlled vocabulary

---

lib/oregon_digital/controlled_vocabularies/vocabularies/ons_base.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_class.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_common_names.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_creator.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_culture.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_genus.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_local_collection_name.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_osu_academic_units.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_osu_buildings.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_phylum.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_repository.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_style_period.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_subject.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_work_type.rb

move duped code to base object

---

.rubocop_fixme.yml
lib/hyrax/controlled_vocabularies/location.rb

Fixes #392 
Fixes #323 
This may not be the exact format we're looking to present location labels, but it fixes the recursion and validation issues.

Location rdf_label fetch fix

---

app/controllers/hyrax/contact_form_controller.rb
app/mailers/oregon_digital/contact_mailer.rb
app/models/oregon_digital/contact_form.rb
app/views/oregon_digital/contact_mailer/contact.html.erb
spec/mailers/oregon_digital/contact_mailer_spec.rb
spec/models/oregon_digital/contact_form_spec.rb

Includes commits for just CC'ing the submitter and a custom message.
@petersec @vantuyls If CC'ing is good enough, it's cleaner code and I can revert to that commit. Otherwise checkout [`app/views/oregon_digital/contact_mailer/contact.html.erb`](https://github.com/OregonDigital/OD2/blob/924a86bea7472a581dfa5578288dd9059235cfe3/app/views/oregon_digital/contact_mailer/contact.html.erb) for the custom message.

Contact form message

---

app/models/concerns/oregon_digital/document_metadata.rb
app/models/concerns/oregon_digital/generic_metadata.rb

~Set repository to multiple: false~
That's more difficult than this ticket. Will open a new issue about it.
Fixes #452 
Fixes #366

Remove extra descriptive metadata

---

app/authorities/qa/authorities/scientific.rb
app/authorities/qa/authorities/subject.rb

Fix subject and scientific controlled vocabularies

---

config/initializers/hyrax.rb

Fixes #357 
Loosely depends on #456

Change admin set predicate

---

lib/oregon_digital/controlled_vocabularies/publisher.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_publisher.rb
spec/authorities/qa/authorities/publisher_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/ons_publisher_spec.rb

Add ONS:Publisher to publisher CV

---

config/locales/generic.en.yml

Fix Donor facet label

---

public/robots.txt

Update robots.txt - disallow indexing

---

.circleci/config.yml
app/views/shared/_footer.html.erb

make footer include OD2 version always

---

lib/oregon_digital.rb

autoload the featureclassuritolabel class

---

app/models/concerns/oregon_digital/document_metadata.rb
app/models/concerns/oregon_digital/image_metadata.rb
app/models/concerns/oregon_digital/video_metadata.rb
app/views/hyrax/base/_attribute_rows.html.erb
spec/models/document_spec.rb
spec/models/image_spec.rb
spec/models/video_spec.rb

fixes lingering data in new methods

---

config/locales/generic.en.yml

Update Rights field form help text

---

config/initializers/migrator/admin_sets_info.yml
lib/tasks/oregon_digital/create_admin_sets.rake

fixes https://github.com/OregonDigital/hyrax-migrator/issues/86

add create_admin_sets task

---

app/controllers/catalog_controller.rb
app/indexers/generic_indexer.rb
app/models/solr_document.rb
app/presenters/hyrax/generic_presenter.rb
app/services/oregon_digital/language_service.rb
app/services/oregon_digital/license_service.rb
app/services/oregon_digital/rights_statement_service.rb
app/services/oregon_digital/type_service.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/records/edit_fields/_repository.html.erb
spec/indexers/generic_indexer_spec.rb
spec/services/oregon_digital/language_service_spec.rb
spec/services/oregon_digital/license_service_spec.rb
spec/services/oregon_digital/rights_statement_service_spec.rb
spec/services/oregon_digital/type_service_spec.rb

This PR is for fixing and updating the search functionality. Some facets are still showing up as uris, some search fields arent working, and some search results still show up as uris.

Fix Search Results and Facets

---

app/controllers/catalog_controller.rb

This is to dial back the changes to the catalog controller so that we arent changing too many things at once. Then we can further refine the catalog controller as we get closer to knowing exactly what we want to search for

update to only add known indexed items

---

app/forms/hyrax/generic_form.rb
spec/forms/hyrax/generic_form_spec.rb
spec/models/generic_spec.rb

adds cvs back to form

---

config/locales/hyrax.en.yml

Fix Interviewer spelling

---

app/models/audio.rb
app/models/document.rb
app/models/generic.rb
app/models/image.rb
app/models/video.rb

Fix retry fetch linked data queue
Fixes #552, Fixes #312

Fix non-generic works saving

---

app/assets/javascripts/oregon_digital/collections/configurable_facets.js

Remove backticks from JS

---

spec/support/system.rb

add w3c option to selenium setup

---

app/helpers/catalog_helper.rb
app/helpers/oregon_digital/configuration_helper_behavior.rb
app/models/collection.rb
app/views/hyrax/collections/_facets.html.erb
app/views/hyrax/dashboard/collections/_form_facets.html.erb
config/initializers/hacks/blacklight_configuration_helper_behavior.rb
config/initializers/hacks/hyrax_collections_controller_behavior.rb
config/locales/hyrax.en.yml
spec/helpers/oregon_digital/configuration_helper_behavior_spec.rb
spec/models/collection_spec.rb

Display facets on collections landing page

---

config/routes.rb

Move collections routes to after Hyrax engine mount

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/hyrax.scss
app/assets/stylesheets/oregon_digital/_home-page.scss
app/assets/stylesheets/oregon_digital/_recent.scss
app/controllers/hyrax/homepage_controller.rb
app/views/_controls.html.erb
app/views/_masthead.html.erb
app/views/_user_util_links.html.erb
app/views/catalog/_search_form.html.erb
app/views/hyrax/homepage/_announcement.html.erb
app/views/hyrax/homepage/_explore_collections.html.erb
app/views/hyrax/homepage/_featured.html.erb
app/views/hyrax/homepage/_featured_fields.html.erb
app/views/hyrax/homepage/_featured_researcher.html.erb
app/views/hyrax/homepage/_featured_works.html.erb
app/views/hyrax/homepage/_home_content.html.erb
app/views/hyrax/homepage/_marketing.html.erb
app/views/hyrax/homepage/_recent_document.html.erb
app/views/hyrax/homepage/_recently_uploaded.html.erb
app/views/hyrax/homepage/_sortable_featured.html.erb
app/views/hyrax/homepage/index.html.erb
app/views/layouts/homepage.html.erb
config/initializers/hyrax.rb
config/locales/hyrax.en.yml
config/locales/oregon_digital.en.yml
spec/controllers/hyrax/homepage_controller_spec.rb

First pass at #520 
Educator and Researcher buttons don't work, collections and items do.

Homepage Design

---

Gemfile.lock
config/initializers/hyrax_migrator.rb
docker-compose.yml

- update hyrax-migrator gem
- update hyrax-migrator initializers for new config settings and environment variables
- add FileIdentityActor actor (to get checksums) to actor_stack

update od2 initializers and hyrax-migrator gem

---

app/assets/stylesheets/oregon_digital/forms.scss
app/inputs/single_value_controlled_vocabulary_input.rb

fixes style for repository

---

config/locales/hyrax.en.yml

update label for human readable type

---

.rubocop_fixme.yml
lib/oregon_digital/controlled_vocabularies/subject.rb

updates subject label fetching

---

.circleci/config.yml

Pin circle image to Debian 9

---

app/assets/stylesheets/oregon_digital/_files-sets.scss
app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/_items.html.erb
app/views/hyrax/base/_member.html.erb
app/views/hyrax/base/_work_title.html.erb
app/views/hyrax/base/show.html.erb
config/locales/hyrax.en.yml

Fixes #604 
Fixes #607 
Start two-column design from wireframes.

Restructure work show page overall

---

app/presenters/hyrax/generic_presenter.rb
app/views/hyrax/base/_show_actions.html.erb

Fixes #604
Adds button next to other actions. Only visible to logged in users.

Create placeholder add to shelf button on work show page

---

app/assets/stylesheets/oregon_digital/_header.scss
app/views/hyrax/base/_work_title.html.erb

Fixes #603 mostly
We don't have a curator role yet, this gives us a way to do it when we do

Hide badges for non-admins

---

app/controllers/catalog_controller.rb
app/forms/hyrax/generic_form.rb
app/models/concerns/oregon_digital/document_metadata.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/models/concerns/oregon_digital/image_metadata.rb
app/models/concerns/oregon_digital/video_metadata.rb
app/models/document.rb
app/views/hyrax/base/_attribute_rows.html.erb
app/views/records/edit_fields/_place_of_production.html.erb
app/views/records/edit_fields/_publication_place.html.erb

update show page with more data

---

app/helpers/hyrax/citations_behavior.rb
app/helpers/oregon_digital/citations_behaviors/formatters/mla_formatter.rb
app/helpers/oregon_digital/citations_behaviors/name_behavior.rb
app/helpers/oregon_digital/citations_behaviors/publication_behavior.rb
app/views/hyrax/base/_citations.html.erb
app/views/hyrax/base/show.html.erb
config/initializers/hyrax.rb
config/locales/hyrax.en.yml
spec/helpers/oregon_digital/citations_behaviors/formatters/mla_formatter_spec.rb

Add MLA Citation section to work show page

---

.rubocop_fixme.yml
lib/oregon_digital/controlled_vocabularies/resource.rb
lib/oregon_digital/controlled_vocabularies/subject.rb

This just updates resource to use the language lable, so all vocabs adhere to this.

move solrize deeper to work for all vocabs

---

app/views/_user_util_links.html.erb

switch change your password to help

---

app/assets/stylesheets/oregon_digital/_home-page.scss
app/views/_user_util_links.html.erb

add text to login buttons

---

app/views/hyrax/base/_show_actions.html.erb

Remove requirement to be logged in to see Add to My Shelf button

---

app/views/hyrax/base/_member.html.erb
config/locales/hyrax.en.yml

adds download links

---

app/controllers/catalog_controller.rb

Fix unicode escaping in catalog_controller

---

app/helpers/oregon_digital/citations_behaviors/formatters/mla_formatter.rb

Present original request URL in MLA format

---

app/models/solr_document.rb
app/presenters/hyrax/generic_presenter.rb
app/renderers/search_and_external_link_attribute_renderer.rb
app/views/hyrax/base/_attribute_rows.html.erb
spec/renderers/hyrax/renderers/search_and_external_link_attribute_renderer_spec.rb

Add search_and_external_link attribute renderer

---

app/views/hyrax/homepage/_home_content.html.erb

remove educator researcher buttons

---

config/locales/hyrax.en.yml

open content

---

app/assets/stylesheets/oregon_digital/_home-page.scss
app/views/_controls.html.erb

adds new buttons to placeholder pages

---

app/views/hyrax/homepage/index.html.erb

remove the share your work button

---

app/assets/stylesheets/oregon_digital/_home-page.scss
app/assets/stylesheets/oregon_digital/_recent.scss
app/views/hyrax/homepage/_curated_showcases.html.erb
app/views/hyrax/homepage/_fixed_showcases.html.erb
app/views/hyrax/homepage/_how_to_use.html.erb
app/views/hyrax/homepage/_showcase_tile.html.erb

Improve homepage layout

---

app/models/concerns/oregon_digital/work_behavior.rb
spec/models/generic_spec.rb

Fixes #668 
Grabs first file from each file_set, stringifies the bytes, zips those together with csv metadata

Zip work files

---

app/controllers/application_controller.rb

Fix beeline-ruby namespacing

---

app/controllers/catalog_controller.rb

Remove masonry and slideshow views from search

---

Gemfile.lock

update hyrax-migrator to get skip field mode feature

update hyrax-migrator to get latest updates

---

app/assets/stylesheets/oregon_digital/_footer.scss
app/views/shared/_footer.html.erb

update hover and underline

---

app/forms/hyrax/generic_form.rb
app/models/concerns/oregon_digital/generic_metadata.rb
spec/controllers/hyrax/homepage_controller_spec.rb
spec/factories/audios.rb
spec/factories/documents.rb
spec/factories/generic_works.rb
spec/factories/generics.rb
spec/factories/images.rb
spec/factories/videos.rb
spec/helpers/oregon_digital/citations_behaviors/formatters/mla_formatter_spec.rb
spec/indexers/audio_indexer_spec.rb
spec/indexers/document_indexer_spec.rb
spec/indexers/generic_indexer_spec.rb
spec/indexers/image_indexer_spec.rb
spec/indexers/video_indexer_spec.rb
spec/system/create_audio_spec.rb
spec/system/create_document_spec.rb
spec/system/create_generic_spec.rb
spec/system/create_image_spec.rb
spec/system/create_video_spec.rb

Revert "update repository to single value (#649)"

---

app/views/catalog/_index_header_list_collection.html.erb
app/views/catalog/_index_header_list_default.html.erb

Truncate search result titles to 10 words

---

app/controllers/catalog_controller.rb
app/models/concerns/oregon_digital/document_metadata.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/models/concerns/oregon_digital/image_metadata.rb
app/models/concerns/oregon_digital/video_metadata.rb

Fixes #629 
Need to update code to work with `showable: false`

Catalog Controller Untangling

---

config/initializers/honeycomb.rb
docker-compose.yml

Disable honeycomb in debug environments

---

app/controllers/catalog_controller.rb

Search list view: Move work title over

---

app/assets/stylesheets/oregon_digital/bootstrap/_type.scss
app/views/catalog/_index_list_default.html.erb

Search List view: Left align metadata labels

---

app/controllers/catalog_controller.rb
app/presenters/blacklight/rendering/max_length.rb
app/presenters/blacklight/rendering/max_values.rb
app/views/catalog/_index_gallery_default.html.erb

Search Gallery view: Metadata field labels

---

app/views/catalog/_index_header_gallery_collection.html.erb
app/views/catalog/_index_header_gallery_default.html.erb

Search Gallery view: Truncate titles to 5 words

---

app/views/hyrax/base/_file_manager_member.html.erb

Fix file manager view crashing on label truncate

---

app/views/catalog/_index_header_gallery_default.html.erb
app/views/catalog/index.html.erb
app/views/hyrax/collections/show.html.erb

Render facets before search results in HTML

---

app/assets/stylesheets/oregon_digital/_search.scss
app/views/_controls.html.erb
app/views/catalog/_index_header_gallery_collection.html.erb
app/views/catalog/_index_header_gallery_default.html.erb
app/views/catalog/_index_header_list_collection.html.erb
app/views/catalog/_index_header_list_default.html.erb

Adds myshelf elements

---

app/views/catalog/_search_results.html.erb
spec/system/search_accessibility_spec.rb

Search page a11y specs

---

app/assets/javascripts/oregon_digital/add_to_my_shelf.js
app/assets/stylesheets/oregon_digital/_search.scss
app/views/_controls.html.erb
app/views/catalog/_index_gallery_default.html.erb
app/views/catalog/_index_header_gallery_collection.html.erb
app/views/catalog/_index_header_gallery_default.html.erb
app/views/catalog/_index_header_list_collection.html.erb
app/views/catalog/_index_header_list_default.html.erb
app/views/catalog/_index_list_default.html.erb

js for checking boxes and checkbox positioning

---

config/sidekiq.yml

Add named queue:  `hyrax_migrator` and set concurrency to 5

add config sidekiq for named queues

---

build/entrypoint.sh
build/firstrun.sh
config/roles.yml
lib/tasks/oregon_digital/create_roles.rake

Create initial OD2 Roles

---

.rubocop_fixme.yml
app/assets/stylesheets/oregon_digital/forms.scss
app/models/ability.rb
app/models/concerns/oregon_digital/ability/work_edit_ability.rb
app/models/user.rb
spec/controllers/oregon_digital/oembeds_controller_spec.rb
spec/models/ability_spec.rb
spec/rails_helper.rb
spec/system/create_audio_spec.rb
spec/system/create_document_spec.rb
spec/system/create_generic_spec.rb
spec/system/create_image_spec.rb
spec/system/create_video_spec.rb

Add work edit permissions

---

app/models/ability.rb
app/models/concerns/oregon_digital/ability/work_delete_ability.rb
spec/models/ability_spec.rb

add delete functionality

---

app/models/concerns/oregon_digital/generic_metadata.rb

Remove extra workType property definition

---

Gemfile.lock

update for hyrax-migrator that includes:
- admin_set_id update in admin_set_membership_service (fixes https://github.com/OregonDigital/hyrax-migrator/pull/146)
- fix for relationships (fixes https://github.com/OregonDigital/hyrax-migrator/issues/141)

update hyrax-migrator gem to update relationships

---

config/initializers/migrator/model_crosswalk.yml

fixes https://github.com/OregonDigital/hyrax-migrator/issues/137

add GenericAsset to model crosswalk

---

.rubocop_fixme.yml
app/controllers/hyrax/generics_controller.rb
app/models/ability.rb
app/models/concerns/oregon_digital/ability/work_review_ability.rb
app/models/concerns/oregon_digital/ability/work_show_ability.rb
app/views/hyrax/base/show.html.erb

This is the basis for the work that needs to be done. Collection Managers need to be able to review works in their collections. We need to be able to see what collection a work is a part of and see if the person viewing that work is a collection manager for that work. This is merely the beginning work into discovering how to pass variables into an ability.

work on setting up initial ability for review

---

Gemfile.lock

- update hyrax-migrator to get update for #145 
- related PR https://github.com/OregonDigital/hyrax-migrator/pull/147

update hyrax migrator gem to add uri check

---

lib/oregon_digital/controlled_vocabularies/institution.rb

update institution vocab

---

app/models/concerns/oregon_digital/ability/work_review_ability.rb
app/models/oregon_digital/solr_document_behavior.rb
app/views/hyrax/admin/workflows/index.html.erb

Restrict shown works on review task page

---

config/authorities/licenses.yml

Add opns rights/rr-f to licenses

---

config/authorities/licenses.yml

Reverts OregonDigital/OD2#800
https://github.com/OregonDigital/hyrax-migrator/pull/151 would be used in place

Revert "Add opns rights/rr-f to licenses"

---

app/views/roles/edit.html.erb
app/views/roles/index.html.erb

updates view to be a bit more readable

---

Gemfile.lock

update gem to get the update https://github.com/OregonDigital/hyrax-migrator/pull/153

update hyrax migrator oct 18

---

app/controllers/users/registrations_controller.rb
app/services/oregon_digital/user_attribute_service.rb
spec/services/oregon_digital/user_attribute_service_spec.rb

Flash authentication error to university affiliates

---

app/views/roles/edit.html.erb

remove ability to edit title for role

---

app/views/catalog/_search_form.html.erb

adds aria lables based on the real label

---

app/views/hyrax/homepage/_curated_showcases.html.erb

Empty collection image alt tags

---

Dockerfile
app/views/shared/_footer.html.erb

install zip

---

app/assets/stylesheets/browse_everything.scss

fixes #885 
update scss reference as recommended in https://github.com/samvera/browse-everything#css

update browse_everything scss reference

---

Gemfile.lock
config/initializers/hyrax_migrator.rb
docker-compose.yml

- update gem to get update for https://github.com/OregonDigital/hyrax-migrator/pull/163
- update configuration to set `content_file_can_be_nil` from ENV variables

Update hyrax migrator dec 11 19

---

app/controllers/users/registrations_controller.rb

Prevent community users from seeing university specific registration message

---

app/services/oregon_digital/file_set_derivatives_service.rb
spec/services/oregon_digital/file_set_derivatives_service_spec.rb

Always produce 8bpc intermediate BMPs

---

app/assets/javascripts/hyrax/editor/controlled_vocabulary.es6

Prevent duplicate controlled vocabulary fields from removing original value

---

app/views/catalog/_search_form.html.erb

update to aria label

---

app/controllers/users/passwords_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/services/oregon_digital/user_attribute_service.rb
app/views/_user_util_links.html.erb
config/routes.rb

Prevent institutional user change or recover password

---

Gemfile.lock

update gem to bring updates https://github.com/OregonDigital/hyrax-migrator/pull/168 and https://github.com/OregonDigital/hyrax-migrator/pull/166

update hyrax-migrator 1-9-20

---

config/initializers/migrator/admin_sets_info.yml

This adds the new admin sets to the admin_sets_info.yml, partially fulfilling https://github.com/OregonDigital/hyrax-migrator/issues/115

fix typos in yml

---

app/indexers/oregon_digital/deep_indexing_service.rb
lib/oregon_digital/triplestore.rb

Fixes #934 
Also removes temporary graph cache benchmarking code.

Fix indexer logging about cache & authorative source

---

config/initializers/migrator/crosswalk_admin_sets.yml

fixes #https://github.com/OregonDigital/hyrax-migrator/issues/115

update uo admin sets

---

app/models/audio.rb
app/models/document.rb
app/models/image.rb
app/models/video.rb
spec/factories/audios.rb
spec/factories/documents.rb
spec/factories/images.rb
spec/factories/videos.rb

Set required fields on form to be required on more models

---

app/authorities/qa/authorities/access_restrictions.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/views/records/edit_fields/_access_restrictions.html.erb
lib/oregon_digital/controlled_vocabularies/access_restrictions.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ons_access_restrictions.rb
spec/oregon_digital/controlled_vocabularies/access_restrictions_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/ons_access_restrictions_spec.rb

make access restrictions controlled

---

app/models/audio.rb
app/models/concerns/oregon_digital/work_behavior.rb
app/models/document.rb
app/models/generic.rb
app/models/image.rb
app/models/video.rb

Change required field references to literal list

---

config/initializers/migrator/crosswalk_overrides.yml

fixes https://github.com/OregonDigital/OD2/issues/977

add changing predicates

---

.rubocop_fixme.yml
spec/controllers/users/omniauth_callbacks_controller_spec.rb

Small fix to clean up some specs

update spec to remove instance variable

---

Gemfile.lock

update hyrax-migrator gem to bring update and bugfix:
https://github.com/OregonDigital/hyrax-migrator/pull/182
https://github.com/OregonDigital/hyrax-migrator/pull/185

update hyrax-migrator gem 2-14-20

---

config/locales/generic.en.yml
config/locales/hyrax.en.yml

This PR addresses the label issues found here: https://github.com/OregonDigital/OD2/issues/764

updates the show page to show proper labels

---

app/views/hyrax/base/_metadata.html.erb

Remove second instance of license metadata

---

app/workers/fetch_graph_worker.rb
spec/workers/fetch_graph_worker_spec.rb

Combined creator indexing

---

app/controllers/catalog_controller.rb
app/models/concerns/oregon_digital/generic_metadata.rb
config/locales/generic.en.yml

Combined creator facet

---

app/controllers/catalog_controller.rb
app/models/concerns/oregon_digital/generic_metadata.rb
config/locales/generic.en.yml

updates the locations to not facet. Combined facet displayed

---

app/indexers/generic_indexer.rb
app/workers/fetch_graph_worker.rb
spec/workers/fetch_graph_worker_spec.rb

Combined topic indexing

---

app/controllers/catalog_controller.rb
app/models/concerns/oregon_digital/generic_metadata.rb
config/locales/generic.en.yml

Display combined facet for topic

---

app/controllers/catalog_controller.rb
app/models/concerns/oregon_digital/generic_metadata.rb
config/locales/generic.en.yml

configure facet to use combined copyright

---

app/indexers/generic_indexer.rb
spec/workers/fetch_graph_worker_spec.rb

Index dates into combined date field

---

app/controllers/catalog_controller.rb
app/models/concerns/oregon_digital/generic_metadata.rb
config/locales/generic.en.yml

Display combined facet for date

---

app/models/concerns/oregon_digital/generic_metadata.rb
app/models/concerns/oregon_digital/image_metadata.rb

More showpage metadata

---

config/initializers/hyrax.rb

Enable full text extraction of files

---

app/controllers/catalog_controller.rb
app/indexers/generic_indexer.rb

File format indexing and facet

---

app/views/hyrax/file_sets/show.html.erb

Only display user activity on fileset display page if user is logged in and is admin

---

app/views/hyrax/base/_form_visibility_component.html.erb

update strings in view to use objects that load

---

app/forms/hyrax/generic_form.rb
app/indexers/generic_indexer.rb

Revert indexing and remove dates from form

---

lib/oregon_digital/fedora_finder.rb
lib/tasks/oregon_digital/reindex_all.rake

Closes #1102 
This is important so the task doesn't appear to be completely hung when
running it on the command line

Add output to reindexer

---

app/models/solr_document.rb
app/search_builders/oregon_digital/parents_of_work_search_builder.rb
app/views/catalog/_index_list_default.html.erb
config/locales/generic.en.yml
spec/search_builders/oregon_digital/parents_of_work_search_builder_spec.rb

Parent links on child works search results

---

app/renderers/search_and_external_link_attribute_renderer.rb

Remove any _label fields on show page for generated search and external links

---

app/controllers/catalog_controller.rb
app/views/catalog/_search_form.html.erb
app/views/hyrax/homepage/_fixed_showcases.html.erb

Expand open access filter to include all Public Domain and Creative Common licenses

---

app/presenters/hyrax/generic_presenter.rb
app/views/hyrax/base/_representative_media.html.erb

Display IIIF viewer if child has IIIF viewable images

---

.circleci/config.yml
Dockerfile

Move to CircleCI docker orb and improve image building caching

---

app/models/user.rb

update to not send email and rely on confirmation if university login

---

app/models/concerns/oregon_digital/document_metadata.rb
app/models/concerns/oregon_digital/generic_metadata.rb
config/locales/document.en.yml
config/locales/generic.en.yml

Add On Pages metadata to document model

---

app/models/user.rb

Refactor + confirmation notification check.

update to make confirmation decision

---

lib/hyrax/controlled_vocabularies/location.rb
spec/hyrax/controlled_vocabularies/location_spec.rb

Stop geonames parent search when rdf_subject is https

---

lib/hyrax/controlled_vocabularies/location.rb

Fix county not pulling in parent hierarchy

---

app/models/concerns/oregon_digital/ability/collection_ability.rb
app/views/hyrax/dashboard/collections/_form.html.erb

Allow user to create user collection

---

app/views/hyrax/base/_show_actions.html.erb
app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb
app/views/oregon_digital/dashboard/collections/_form_for_create_collection.html.erb
config/initializers/hacks/hyrax_collections_controller.rb
config/locales/oregon_digital.en.yml

Collection creation modal for non-admin users

---

app/views/catalog/_index_gallery_default.html.erb
app/views/catalog/_index_list_default.html.erb
app/views/catalog/_sort_and_per_page.html.erb

Initial work for modal on search results page.
Still need to fix some CSS and make the button text toggle when one search result is present vs many

override sortandperpage and add modal

---

app/assets/stylesheets/oregon_digital/bootstrap/_modals.scss
app/views/catalog/_index_gallery_default.html.erb
app/views/catalog/_index_list_default.html.erb
app/views/catalog/_search_results.html.erb
app/views/oregon_digital/dashboard/collections/_form_for_create_collection.html.erb

fixes modal for scrolling and allows collection create to work

---

app/views/oregon_digital/explore_collections/_display_mode_buttons.html.erb
app/views/oregon_digital/explore_collections/index.html.erb
config/locales/oregon_digital.en.yml

Fixes #1153 
Adds the create collection button and modal to the explore collection dashboard

Add create collection option to explore collection menu

---

Gemfile.lock
config/initializers/hyrax_migrator.rb
config/initializers/migrator/required_fields.yml

hyrax-migrator gem updates:
- Verify required [https://github.com/OregonDigital/hyrax-migrator/pull/204](https://github.com/OregonDigital/hyrax-migrator/pull/204) by lsat12357
- updated configurations as required in https://github.com/OregonDigital/hyrax-migrator/pull/204#issuecomment-618483165

hyrax-migrator update 6-3-20 (verify required)

---

app/views/catalog/_document.html.erb

saves work based on which are checked.

---

app/assets/javascripts/oregon_digital/collections/explore_collections_edit_modal.js
app/views/oregon_digital/explore_collections/_actions_list.html.erb
app/views/oregon_digital/explore_collections/_form_for_delete_collection.html.erb
app/views/oregon_digital/explore_collections/index.html.erb
config/initializers/hacks/hyrax_collections_controller.rb
config/locales/hyrax.en.yml
config/locales/oregon_digital.en.yml

Delete action for explore collections

---

app/assets/javascripts/oregon_digital/collections/update_save_checkboxes.js
app/views/_controls.html.erb
app/views/catalog/_index_list_default.html.erb

updates to add js that is linked to single save button

---

app/assets/javascripts/oregon_digital/collections/explore_collections_edit_modal.js
config/initializers/hacks/hyrax_collections_members_controller.rb

Fix after update redirect when adding items to a collection

---

app/views/hyrax/dashboard/collections/_form.html.erb

Move thumbnail into non-user form

---

app/assets/javascripts/oregon_digital/add_to_my_shelf.js
app/assets/javascripts/oregon_digital/collections/update_save_checkboxes.js
app/views/catalog/_sort_and_per_page.html.erb

Fixes #1193 
QA: On search results page, Select/Revome buttons next to the "Save Selected To" button should check/uncheck all check boxes.

updates page to have select and deselect all

---

app/assets/stylesheets/oregon_digital/_search.scss
app/views/catalog/_sort_and_per_page.html.erb
config/locales/hyrax.en.yml

update css for buttons and works for one less than 10000000

---

app/assets/javascripts/oregon_digital/collections/explore_collections_modals.js
app/assets/stylesheets/oregon_digital/collections/explore_collections.scss
app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb
app/views/oregon_digital/explore_collections/_actions_list.html.erb
app/views/oregon_digital/explore_collections/_form_for_delete_collection.html.erb
app/views/oregon_digital/explore_collections/_form_for_share_collection.html.erb
app/views/oregon_digital/explore_collections/_form_for_unshare_collection.html.erb
app/views/oregon_digital/explore_collections/_share_link_clipboard.html.erb
app/views/oregon_digital/explore_collections/index.html.erb
config/locales/hyrax.en.yml
config/locales/oregon_digital.en.yml

My collection visibility toggle and share url

---

app/workers/fetch_graph_worker.rb
config/initializers/oregon_digital_listeners.rb

lower duration of time for commits and commit sooner

---

app/assets/javascripts/oregon_digital/collections/explore_collections_modals.js
app/models/collection.rb
app/models/concerns/oregon_digital/collection_behavior.rb
app/views/oregon_digital/explore_collections/_actions_list.html.erb
app/views/oregon_digital/explore_collections/_form_for_export_collection.html.erb
app/views/oregon_digital/explore_collections/index.html.erb
config/initializers/hacks/hyrax_collections_controller_behavior.rb
config/locales/hyrax.en.yml
config/locales/oregon_digital.en.yml
config/routes.rb
spec/models/collection_spec.rb

Add export action to my collections

---

app/controllers/catalog_controller.rb
app/search_builders/oregon_digital/catalog_search_builder.rb
app/search_builders/oregon_digital/non_user_collections_search_builder.rb
app/search_builders/oregon_digital/only_non_user_collections_behavior.rb
spec/factories/collection_type.rb
spec/system/search_accessibility_spec.rb

refactor user collection filter and include in new search

---

app/controllers/hyrax/audios_controller.rb

Fixes #1172 
For audio work downloads

Add download methods to audio controller

---

config/initializers/migrator/fields_map.yml

some properties renamed in  OD2

get name changes

---

app/models/concerns/oregon_digital/ability/collection_ability.rb
app/models/concerns/oregon_digital/ability/work_download_ability.rb
app/models/concerns/oregon_digital/collection_behavior.rb
config/initializers/hacks/hyrax_collections_controller_behavior.rb
config/initializers/hacks/hyrax_collections_members_controller.rb

Permissions fixes and subcollection downloading

---

app/helpers/catalog_helper.rb
app/helpers/oregon_digital/facet_helper_behavior.rb

Filters user collections from facet item list

---

config/initializers/migrator/crosswalk_admin_sets.yml

related to https://github.com/OregonDigital/hyrax-migrator/issues/219

add institution uris for uo and osu admin sets

---

app/controllers/catalog_controller.rb
app/indexers/generic_indexer.rb

update works to index collections into new field used for facets

---

app/models/concerns/oregon_digital/collection_behavior.rb

Pass current_ability through collection zipping methods

---

app/jobs/bulk_approve_job.rb
app/workers/fetch_failed_graph_worker.rb
app/workers/fetch_graph_worker.rb
config/initializers/hacks/hyrax_collections_controller.rb
lib/tasks/migration/bulk_approve.rake

& Update ActiveFedora::SolrService to Hyrax::SolrService
Fixes #1231

Make sure keyword_tesim is an array

---

app/assets/stylesheets/oregon_digital/_search.scss
app/views/catalog/_index_gallery.html.erb

updates layout for the index

---

app/models/concerns/oregon_digital/collection_metadata.rb

Set license metadata field on collection to be single value

---

app/views/catalog/_index_gallery_default.html.erb
app/views/catalog/_index_list_default.html.erb

updates to check if type label exists

---

app/assets/javascripts/oregon_digital/collections/explore_collections_modals.js
app/views/oregon_digital/explore_collections/_actions_list.html.erb

Replace missing data-delete-url value

---

config/environments/production.rb

Quick fix to deploy issue from #1260

Change JS compressor to support es6 syntax

---

build/entrypoint.sh

Move yarn install outside of production exemption block of entrypoint script

---

app/assets/javascripts/oregon_digital/collections/explore_collections_modals.js
app/services/oregon_digital/listeners/metadata_fetch_listener.rb
app/views/oregon_digital/dashboard/collections/_form_for_create_collection.html.erb
app/views/oregon_digital/explore_collections/_form_for_delete_collection.html.erb
config/initializers/oregon_digital_listeners.rb

User collection delete & new by ajax. Pub-Sub fetch graph workers

---

Dockerfile

Whatever... a justification or something
Fixes #1262

Yarn install at the end of the asset process

---

app/views/oregon_digital/explore_collections/_actions_list.html.erb

Remove three dot action expansion, fix some IDs, center copy box

---

app/authorities/qa/authorities/creator.rb
lib/oregon_digital/controlled_vocabularies/creator.rb
lib/oregon_digital/controlled_vocabularies/publisher.rb
lib/oregon_digital/controlled_vocabularies/scientific.rb
lib/oregon_digital/controlled_vocabularies/subject.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/wikidata.rb
spec/authorities/qa/authorities/creator_spec.rb
spec/authorities/qa/authorities/subject_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/wikidata_spec.rb

Add wikidata vocabulary to Publisher CV

---

app/presenters/oregon_digital/iiif_presenter.rb
config/uv/uv-config.json

Configure UV for downloads and paged viewing

---

config/uv/uv-config.json

Restrict UV locales

---

Gemfile.lock

get fix to visibility lookup on migrator gem https://github.com/OregonDigital/hyrax-migrator/pull/230

update migrator et al

---

app/views/hyrax/base/_embed.html.erb
app/views/hyrax/base/_items.html.erb

Add UV embed option to downloads section

---

config/initializers/migrator/crosswalk_admin_sets.yml

fixes https://github.com/OregonDigital/hyrax-migrator/issues/228

fix missing set

---

Gemfile
Gemfile.lock
app/controllers/concerns/oregon_digital/download_controller_behavior.rb
app/models/concerns/oregon_digital/collection_behavior.rb
app/models/concerns/oregon_digital/work_behavior.rb
app/services/oregon_digital/collection_streamer.rb
app/services/oregon_digital/file_set_streamer.rb
config/initializers/hacks/hyrax_collections_controller_behavior.rb
spec/models/generic_spec.rb
spec/services/oregon_digital/collection_streamer_spec.rb
spec/services/oregon_digital/file_set_streamer_spec.rb

Stream zipped downloads of works and collections

---

app/controllers/blacklight/oembed/embed_controller.rb
app/controllers/hyrax/generics_controller.rb
app/indexers/oregon_digital/file_set_indexer.rb
app/models/concerns/oregon_digital/work_behavior.rb
app/models/file_set.rb
app/search_builders/oregon_digital/oembed_search_builder.rb
app/views/oregon_digital/oembeds/_table.html.erb
app/views/oregon_digital/oembeds/index.html.erb
spec/search_builders/oregon_digital/oembed_search_builder_spec.rb
spec/services/oregon_digital/oembed_service_spec.rb

Fix OembedErrors for FileSets

---

app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/_show_actions.html.erb

final touches on show page

---

app/actors/oregon_digital/actors/create_with_oembed_url_actor.rb
app/models/search_builder.rb
config/initializers/hacks/hyrax_file_set_edit_form.rb

Fix unavailable error with unreviewed works
Fixes #1346

Catch oEmbed errors when creating fileset

---

app/models/concerns/oregon_digital/ability/work_download_ability.rb

Allow metadata to be downloaded

---

app/assets/stylesheets/oregon_digital/_header.scss
app/assets/stylesheets/oregon_digital/fonts.scss
app/assets/stylesheets/oregon_digital/utils.scss
app/views/_logo.html.erb
app/views/_masthead.html.erb
app/views/_user_util_links.html.erb
app/views/shared/_header_search.html.erb

Adds mobile view for header and other improvements
Fixes #1337

Further header sizing and mobile improvments

---

app/assets/stylesheets/oregon_digital/_buttons.scss
app/assets/stylesheets/oregon_digital/collections/show.scss
app/views/catalog/_search_results.html.erb
app/views/layouts/hyrax/1_column.html.erb

Collection landing remove search bar, reduce sizing and spacing

---

app/assets/stylesheets/oregon_digital/_header.scss
app/assets/stylesheets/oregon_digital/explore_collections/_buttons.scss
app/assets/stylesheets/oregon_digital/explore_collections/_showcase.scss
app/assets/stylesheets/oregon_digital/fonts.scss
app/views/_masthead.html.erb
app/views/_user_util_links.html.erb
app/views/oregon_digital/explore_collections/_list_showcase.html.erb
app/views/oregon_digital/explore_collections/_showcase_tile.html.erb
app/views/oregon_digital/explore_collections/index.html.erb

More Explore Collections Views Improvements

---

app/assets/stylesheets/oregon_digital/_search.scss
app/controllers/catalog_controller.rb
app/models/solr_document.rb
app/views/catalog/_index_header_gallery_collection.html.erb
app/views/catalog/_index_header_gallery_default.html.erb
app/views/catalog/_index_header_list_collection.html.erb
app/views/catalog/_index_header_list_default.html.erb
app/views/catalog/_index_list_default.html.erb
app/views/catalog/_index_type_icon.html.erb
config/locales/generic.en.yml

Part of the work for #1376 
Shows compoundedness and relocates the rights statement and other metadata

Compound objects in search results list view

---

app/assets/stylesheets/oregon_digital/_search.scss
app/assets/stylesheets/oregon_digital/fonts.scss
app/controllers/catalog_controller.rb
app/views/catalog/_constraints.html.erb
app/views/catalog/_constraints_element.html.erb
app/views/catalog/_index_list_default.html.erb
app/views/catalog/_per_page_widget.html.erb
app/views/catalog/_search_results.html.erb
app/views/catalog/_sort_and_per_page.html.erb
app/views/catalog/_sort_widget.html.erb
app/views/catalog/index.html.erb
config/initializers/_i18n.rb
config/locales/blacklight.en.yml

More work for #1376 and shared with #1377
Includes constraints moved to the top of the search header
sort/show/save buttons in the right order/position
and fixes a missing nil check on rights statement

Search results header for list and grid views

---

app/assets/stylesheets/oregon_digital/_search.scss
app/views/catalog/_index_list_default.html.erb
app/views/catalog/_sort_and_per_page.html.erb
app/views/kaminari/blacklight/_next_page.html.erb
app/views/kaminari/blacklight/_paginator.html.erb
app/views/kaminari/blacklight/_prev_page.html.erb
config/locales/blacklight.en.yml

Some more simple work for #1376 & #1377 
Fixes a bit of the collection display in list mode
Sets pagination to look like screenshot/wireframe

Search pagination

---

app/controllers/oregon_digital/explore_collections_controller.rb

update to fetch max rows

---

app/views/hyrax/base/_work_title.html.erb

Add copyright icon to work show page

---

Gemfile.lock

add changes to verify checksums service to migrator,  see https://github.com/OregonDigital/hyrax-migrator/issues/248

verify checksums

---

app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/_show_collection_header.html.erb

Resize collection preview font and spacing

---

app/assets/stylesheets/oregon_digital/explore_collections/_buttons.scss
app/views/oregon_digital/explore_collections/index.html.erb

Got the arrows in place and toggling, need to refine button sizes.

toggle down arrow for sort buttons

---

app/assets/stylesheets/oregon_digital/bootstrap/_modals.scss
app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb

Save to modal improvements

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/oregon_digital/_search.scss
app/views/catalog/_facets.html.erb
app/views/catalog/_search_form.html.erb
app/views/shared/_header_search.html.erb
config/locales/hyrax.en.yml

Facets search bar and fixes

---

Gemfile.lock

get updated migrator (contains https://github.com/OregonDigital/hyrax-migrator/issues/255, https://github.com/OregonDigital/hyrax-migrator/issues/240)

get facet reporter, tmpdir fix

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/oregon_digital/_search.scss
app/controllers/catalog_controller.rb
app/controllers/search_history_controller.rb
app/models/search_builder.rb
app/views/catalog/_search_sidebar.html.erb
config/routes.rb

Small fix to facets display and install the range select facet gem
Does some work on #1141

Install blacklight_range_limit gem

---

app/assets/stylesheets/oregon_digital/_search.scss
app/views/catalog/_search_sidebar.html.erb

Some more search CSS

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/font_awesome.scss
app/assets/stylesheets/hyrax.scss
app/assets/stylesheets/oregon_digital/_search.scss
app/models/solr_document.rb
app/views/catalog/_document_gallery.html.erb
app/views/catalog/_index_list_default.html.erb
app/views/catalog/_search_sidebar.html.erb
app/views/hyrax/base/_work_title.html.erb

Install fontawesome 5 side-by-side with fontawesome 4

---

app/assets/stylesheets/oregon_digital/_search.scss
app/controllers/catalog_controller.rb

Set search per page to even rows of grid search and improve per page dropdown spacing

---

app/indexers/generic_indexer.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/workers/fetch_graph_worker.rb
config/locales/generic.en.yml

Improve label retrieval on workshow page and facets

---

db/migrate/20210324194640_update_facet_configurable_on_collection_type.rb
db/schema.rb
lib/tasks/oregon_digital/create_collections.rake

Facet configurable by default

---

app/models/collection.rb
app/views/hyrax/dashboard/collections/_form.html.erb

Collections in institution facet and multivalue controlled vocabularies

---

Gemfile.lock

pickup changes for issues:
OregonDigital/hyrax-migrator#272
OregonDigital/hyrax-migrator#268
OregonDigital/hyrax-migrator#267
and the rails update

update migrator ef66f64

---

app/views/hyrax/base/_work_contact_form.html.erb
app/views/hyrax/base/show.html.erb
config/locales/oregon_digital.en.yml

Adds contact form to show page

---

app/controllers/catalog_controller.rb
app/views/catalog/_search_form.html.erb
app/views/hyrax/collections/_search_form.html.erb
app/views/shared/_header_search.html.erb

Multiple keyword searches are 'AND' together

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/controllers/catalog_controller.rb

Roll blacklight range limit back to 6.5.0

---

config/initializers/migrator/collections.yml
lib/tasks/oregon_digital/create_collections.rake

Update collections task

---

app/models/concerns/oregon_digital/generic_metadata.rb

Update fullSizeDownloadAllowed predicate

---

app/models/user.rb
app/views/devise/mailer/confirmation_instructions.html.erb
spec/factories/users.rb

Non-institutional users must confirm their email again

---

.rubocop.yml
app/helpers/hyrax/citations_behavior.rb
app/helpers/oregon_digital/citations_behaviors/formatters/wiki_formatter.rb
app/models/user.rb
app/views/hyrax/base/_citations.html.erb
spec/helpers/oregon_digital/citations_behaviors/formatters/wiki_formatter_spec.rb

Fixes #1551 
Need to refine formatting and add a new base formatter

Initial setup of wiki citation

---

config/initializers/migrator/crosswalk_overrides.yml

workType property needs "_attributes"

needs attributes

---

app/controllers/hyrax/admin/workflows_catalog_behavior.rb
config/initializers/hyrax.rb

Make sure WorkflowsController has the appropriate routes for facets

---

app/models/concerns/oregon_digital/collection_metadata.rb
app/presenters/oregon_digital/collection_presenter.rb

Solize collection_properties on the CollectionPresenter

---

app/views/_controls.html.erb

Fix homepage search to use multiple search queries

---

app/models/concerns/oregon_digital/generic_metadata.rb

add related url back to show page

---

app/indexers/oregon_digital/file_set_indexer.rb
app/models/file_set.rb
app/models/solr_document.rb
app/presenters/hyrax/file_set_presenter.rb
app/views/hyrax/file_sets/_show_details.html.erb

Display more metadata on the File Set page

---

config/initializers/migrator/crosswalk_overrides.yml
config/initializers/migrator/fields_map.yml

some missed changes caught during verification. reran yml generators against the map. also, the overrides is still hand-edited.

remove discarded fields

---

app/controllers/users/confirmations_controller.rb

Redirect non-institutional users to homepage once they register

---

app/views/devise/mailer/confirmation_instructions.html.erb
config/locales/devise.en.yml

Update user confirmation email

---

app/services/oregon_digital/file_set_streamer.rb

Include children of compound objects in download zip

---

config/initializers/migrator/crosswalk_overrides.yml
config/initializers/migrator/fields_map.yml

fixes https://github.com/OregonDigital/hyrax-migrator/issues/287

lose date_modified

---

app/controllers/oregon_digital/explore_collections_controller.rb

I took too much out at the last minute 😆

Add back tab attribute accessor

---

app/models/concerns/oregon_digital/collection_metadata.rb
app/models/concerns/oregon_digital/document_metadata.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/models/concerns/oregon_digital/image_metadata.rb
app/models/concerns/oregon_digital/video_metadata.rb

Update link to Metadata Application Profile (MAP)

---

.github/ISSUE_TEMPLATE/accessibility.yml

Remove label: tags from dropdown options

---

app/models/collection.rb
app/views/hyrax/collections/_advanced_search_facets.html.erb

Reconfigure hidden facets for collection view page

---

app/helpers/hyrax/title_helper.rb

dont use double slash for screen reader

---

app/views/_logo.html.erb

Convert span wrapping h1 to div

---

app/assets/javascripts/oregon_digital/editor.js

Make sure all buttons on ingest form are buttons

---

app/assets/stylesheets/oregon_digital/_header.scss

Fix focus indicator on mobile hamburger menu

---

app/views/advanced/_advanced_search_form.html.erb

Add search role to advanced search form

---

app/views/shared/_header_search.html.erb

Remove one main search label

---

app/views/advanced/_facet_limit.html.erb
app/views/hyrax/homepage/_login_modal.html.erb

Advanced search valid HTML

---

app/helpers/advanced_helper.rb
app/views/advanced/_advanced_search_form.html.erb
spec/system/collection_show_accessibility_spec.rb

Surround advanced search select in label and add aria-description

---

app/assets/javascripts/oregon_digital/user-utils.js
app/assets/stylesheets/blacklight/facet_overrides.scss
app/views/catalog/_facet_layout.html.erb

Update blacklight facet and convert links to buttons

---

app/controllers/concerns/oregon_digital/advanced_controller_index.rb
app/controllers/oregon_digital/explore_collections_controller.rb
config/application.rb
config/locales/hyrax.en.yml
spec/controllers/oregon_digital/explore_collections_controller_spec.rb
spec/features/blacklight_advanced_search_form_spec.rb

add missing breadcrumbs

---

app/assets/stylesheets/oregon_digital/_buttons.scss

Fix hover and focus colors for outline and solid buttons

---

app/helpers/advanced_helper.rb
app/views/advanced/_advanced_search_form.html.erb
app/views/hyrax/collections/_advanced_search_form.html.erb
config/locales/hyrax.en.yml

Updates wording for advanced search and collection show advanced search.

update wording for advanced search to be more accessible

---

app/assets/stylesheets/oregon_digital/_search.scss
app/views/catalog/_facet_layout.html.erb

Also fixes a small CSS bug around facets outside of catalog search
Fixes #1864 
Fixes #1818

Wrap facets in group role

---

app/helpers/hyrax/title_helper.rb

Tried this a couple different ways, but this is ultimately what I felt looked the most organized. If we need to extend the functionality of generating page titles, then we can start thinking about generating an object to help.

advanced search title update

---

app/assets/stylesheets/oregon_digital/fonts.scss
app/views/hyrax/collections/_showcase_tile.html.erb
app/views/hyrax/collections/show.html.erb

Collection headers

---

app/views/catalog/_index_table.html.erb

Ticket #1904: Commit to set collection names as row headers

---

app/views/oregon_digital/explore_collections/_search_form.html.erb

Ticket #1868: Commit to change duplicated ids

---

app/views/hyrax/collections/show.html.erb
config/initializers/hacks/hyrax_collections_controller_behavior.rb

autoscale institution logo and stack thumbnails

---

config/locales/blacklight.en.yml

Remove blacklight <strong> tags in search result counts

---

app/assets/javascripts/oregon_digital/bootstrap-fixes.js

Complies wai-aria-practices Navigtaions Menu Button standard
Fixes #1885

Fix accessibility on Bootstrap dropdown menus

---

.rubocop.yml
app/assets/javascripts/oregon_digital/user-utils.js
app/presenters/hyrax/collapsable_section_presenter.rb

update setting and config to act like disclosure

---

app/views/_user_util_links.html.erb

Remove aria-haspopup from accout menu

---

app/views/advanced/_advanced_search_form.html.erb
app/views/advanced/_advanced_search_help.html.erb
app/views/advanced/_facet_layout.html.erb
app/views/advanced/index.html.erb

Fix advanced search headers

---

app/views/catalog/_facet_layout.html.erb

Add aria-controls to facet accordions

---

app/views/catalog/_thumbnail_list_collection.html.erb
app/views/catalog/_thumbnail_list_default.html.erb

Add alt text to collection and work images

---

app/views/catalog/_search_sidebar.html.erb
app/views/oregon_digital/explore_collections/_sort_and_per_page.html.erb
config/locales/blacklight.en.yml

Wrap blacklight search results numbers in strong tags

---

app/views/catalog/_per_page_widget.html.erb
app/views/catalog/_sort_widget.html.erb

Add aria information to search sort and per page buttons

---

Gemfile.lock

gets fixes/features for crosswalk_metadata_service, verify_labels_exist_service, verify_derifvatives_service

update migrator d77598b

---

app/views/catalog/_document.html.erb
app/views/catalog/_index_gallery.html.erb
app/views/hyrax/dashboard/collections/_list_collections.html.erb
app/views/hyrax/my/collections/_list_collections.html.erb

Aria-labels for bulk collection actions

---

app/views/catalog/_index_gallery.html.erb

Add null alt text to search results

---

app/assets/stylesheets/oregon_digital/_facets.scss

update to not highlight green

---

app/assets/stylesheets/oregon_digital/bootstrap/_modals.scss
app/views/catalog/facet.html.erb
app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb
app/views/hyrax/homepage/_login_modal.html.erb
app/views/oregon_digital/dashboard/collections/_form_for_create_collection.html.erb
app/views/oregon_digital/explore_collections/_form_for_delete_collection.html.erb
app/views/oregon_digital/explore_collections/_form_for_edit_collection.html.erb
app/views/oregon_digital/explore_collections/_form_for_export_collection.html.erb

Modal close button improvement

---

Gemfile.lock

includes fixes for https://github.com/OregonDigital/hyrax-migrator/issues/306, https://github.com/OregonDigital/hyrax-migrator/issues/309

update migrator 73eee90

---

app/assets/javascripts/oregon_digital/collections/masonry.js
app/assets/javascripts/oregon_digital/paginate_explore_collection.js
app/assets/stylesheets/oregon_digital/explore_collections/_actions_list.scss
app/assets/stylesheets/oregon_digital/explore_collections/_masonry_view.scss
app/views/oregon_digital/explore_collections/_actions_list.html.erb
app/views/oregon_digital/explore_collections/_document_masonry.html.erb
app/views/oregon_digital/explore_collections/_index_masonry.html.erb
app/views/oregon_digital/explore_collections/_my_search_results.html.erb
app/views/oregon_digital/explore_collections/_sort_and_per_page.html.erb

My Collection - Masonry

---

app/models/concerns/oregon_digital/generic_metadata.rb

Set isPartOf to DC.isPartOf

---

app/helpers/oregon_digital/citations_behaviors/formatters/chicago_formatter.rb
app/helpers/oregon_digital/citations_behaviors/formatters/mla_formatter.rb

Addresses comments by @kmthorn on https://github.com/OregonDigital/OD2/issues/1551
This adds the spaces requested.

update to add space for mla and chicago

---

Gemfile.lock

brings fixes for 309 (Display profiles)  and 306 (verify checksums)

update migrator a7da807

---

app/views/hyrax/my/_search_form.html.erb

Fix dashboard general search

---

app/views/hyrax/collections/_advanced_search_form.html.erb
app/views/hyrax/collections/_attribute_rows.html.erb
lib/tasks/oregon_digital/create_full_metadata_work.rake

Correctly display collection metadata and facets

---

app/models/concerns/oregon_digital/generic_metadata.rb

Fixes regression from #2097 for #1700

Fix is_part_of predicate regression

---

app/views/oregon_digital/explore_collections/_per_page_widget.html.erb

Update to include more descriptive label and added aria to be menu conformant

---

app/views/catalog/_per_page_widget.html.erb
app/views/catalog/_sort_widget.html.erb
app/views/hyrax/base/_sort_widget.html.erb
app/views/oregon_digital/explore_collections/_per_page_widget.html.erb

Fix more menu widgets

---

app/views/oregon_digital/explore_collections/_explore_tabs.html.erb

Remove My tab if user is not logged in

---

app/views/oregon_digital/explore_collections/_document_table.html.erb

Add table header scopes

---

app/views/_controls.html.erb
app/views/_masthead.html.erb
app/views/layouts/hyrax.html.erb
app/views/oregon_digital/explore_collections/_constraints.html.erb
app/views/oregon_digital/explore_collections/_form_for_delete_collection.html.erb
app/views/oregon_digital/explore_collections/_per_page_widget.html.erb
app/views/oregon_digital/explore_collections/_sort_and_per_page.html.erb
app/views/oregon_digital/explore_collections/index.html.erb

Explore Collections invalid HTML

---

app/views/kaminari/blacklight/_next_page.html.erb
app/views/kaminari/blacklight/_page.html.erb
app/views/kaminari/blacklight/_paginator.html.erb
app/views/kaminari/blacklight/_prev_page.html.erb

with context, current page, and disabled buttons (fixes #1894)

Ticket #1894: Fixed multiple pagination accessibility issues dealing

---

app/views/oregon_digital/explore_collections/_view_type_group.html.erb

table/masonry view buttons (fixes #1884)

Ticket #1884: Commit to fix accessible names and duplication for

---

app/assets/stylesheets/oregon_digital/_search.scss
app/assets/stylesheets/oregon_digital/collections/show.scss
app/views/hyrax/collections/_showcase_tile.html.erb
app/views/hyrax/collections/show.html.erb

Collection landing images align with other image links

---

app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb

Ticket #1829: Commit to edit modal for search "Save Selected" modal

---

app/assets/stylesheets/oregon_digital/_home-page.scss
app/views/hyrax/homepage/_home_content.html.erb

Fixes #1906 
The duplicate h1 had been removed already but the adjustments to the h2 and h4 elements has been made.

Update headings on homepage and adjust css

---

app/assets/javascripts/blacklight/ajax_modal.js
app/views/shared/_ajax_modal.html.erb

Set aria-labelledby to #modal-title after #modal-title exists

---

app/assets/stylesheets/oregon_digital/_search.scss
app/views/catalog/_per_page_widget.html.erb
app/views/catalog/_sort_widget.html.erb

Remove duplicate ids and aria-labelledby on search page

---

app/views/hyrax/collections/_collection_description.erb
app/views/hyrax/collections/show.html.erb

Ticket #1881: Commit to fix recent NU HTML errors on collection show

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb

Fixes #2003 by removing bottom date selections

Remove segments from date range facet

---

app/views/catalog/_search_form.html.erb

Remove second label on search within box

---

app/assets/stylesheets/blacklight/facet_overrides.scss

Wrap words in facets

---

app/assets/javascripts/oregon_digital/collections/update_save_checkboxes.js
app/views/catalog/_sort_and_per_page.html.erb
app/views/hyrax/admin/workflows/_sort_and_per_page.html.erb

Fixes #1970 
This uses aria-live to announce when all checkboxes are selected or deselected

update to use aria live for select/deselect checkboxes

---

app/views/catalog/_constraints.html.erb
app/views/catalog/_per_page_widget.html.erb

Remove duplicated widgets being rendered

---

app/assets/javascripts/hydra-editor/field_manager.es6
app/assets/stylesheets/oregon_digital/_buttons.scss
app/assets/stylesheets/oregon_digital/forms.scss
app/views/oregon_digital/dashboard/collections/_form_for_create_collection.html.erb

Collection creation modal javascript fixes and more

---

app/controllers/catalog_controller.rb

Set catalog search title and include search terms

---

app/views/hyrax/base/_work_contact_form.html.erb

Work show contact form options and heading

---

app/assets/stylesheets/oregon_digital/fonts.scss
app/views/hyrax/base/_data_sources.html.erb
app/views/hyrax/base/_items.html.erb
app/views/hyrax/base/_member.html.erb
app/views/hyrax/users/_activity_log.html.erb

Add captions and row/column headers to work show tables

---

.rubocop.yml
app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
app/inputs/multi_value_input.rb
app/views/catalog/_index_gallery.html.erb
app/views/layouts/hyrax/dashboard.html.erb
app/views/records/edit_fields/_modal_description.html.erb

Ticket #1951: Commit to correct errors from NU Checker on Search page

---

app/views/hyrax/base/_search_results.html.erb

Fixes #2002 
This fixes the h2 issue, the contact form on the show page already has the h3

update the h2 to just be a div with h2 class

---

app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/_items.html.erb
app/views/hyrax/base/_member.html.erb
config/locales/hyrax.en.yml

Work show reflow tables and grids

---

app/assets/javascripts/oregon_digital/paginate-list-view.js
app/assets/javascripts/oregon_digital/pagination_work_show.js
app/assets/javascripts/oregon_digital/work-show-tablist.js
app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/show.html.erb

Work showpage tab panel buttons implemented as disclosure

---

app/helpers/oregon_digital/citations_behaviors/formatters/wiki_formatter.rb
spec/helpers/oregon_digital/citations_behaviors/formatters/wiki_formatter_spec.rb

Fixes #1996 
The other issues were unable to be located on the show page and the linked page was showing an ack message. If these issues popup again, I can go in and locate the code and remove or update them.

remove issues found in NU html checker

---

app/assets/stylesheets/hyrax.scss
app/assets/stylesheets/oregon_digital/_breadcrumbs.scss
app/builders/hyrax/bootstrap_breadcrumbs_builder.rb
app/views/layouts/hyrax.html.erb
app/views/layouts/hyrax/dashboard.html.erb
spec/features/blacklight_advanced_search_form_spec.rb

Move breadcrumb nav out of main content

---

app/views/_controls.html.erb
app/views/catalog/_search_form.html.erb
app/views/hyrax/admin/workflows/_search_form.html.erb
app/views/hyrax/base/_social_media.html.erb
app/views/hyrax/dashboard/_sidebar.html.erb
app/views/oregon_digital/explore_collections/_search_form.html.erb
app/views/shared/_header_search.html.erb
config/locales/blacklight.en.yml
config/locales/hyrax.en.yml

Fixes #2008 
This uses the recommendations from FontAwesome to hide most icon fonts and add labels where they have semantic meaning

Hide and add label to work show font icons

---

app/views/hyrax/base/_show_institution_header.erb

Update alt text for institutional image header

---

app/views/hyrax/base/_print.html.erb
app/views/hyrax/base/_show_actions.html.erb

Convert print link to print button

---

app/views/catalog/_index_gallery.html.erb

Remove checkboxes from work show page works

---

app/assets/javascripts/blacklight/ajax_modal.js
app/assets/stylesheets/oregon_digital/_breadcrumbs.scss
app/controllers/concerns/oregon_digital/works_controller_behavior.rb
app/controllers/hyrax/audios_controller.rb
app/controllers/hyrax/documents_controller.rb
app/controllers/hyrax/generics_controller.rb
app/controllers/hyrax/images_controller.rb
app/controllers/hyrax/videos_controller.rb

There's a couple small fixes in here I found while poking around at the work show page list view fix.
Fixes #1955

A couple small fixes

---

app/assets/stylesheets/oregon_digital/_search.scss
app/assets/stylesheets/oregon_digital/collections/show.scss
app/assets/stylesheets/oregon_digital/explore_collections/_masonry_view.scss
app/views/catalog/_document_gallery.html.erb

Fix up work grid display css

---

app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/_items.html.erb
app/views/hyrax/base/_member.html.erb
app/views/hyrax/base/show.html.erb
app/views/hyrax/users/_activity_log.html.erb

Fixes #2019 
This makes the two tables scrollable and cleans up some render issues

Make file set and user action tables scrollable

---

app/views/layouts/hyrax.html.erb
app/views/layouts/hyrax/dashboard.html.erb

Fix the skip link to go to main content and not be empty

---

app/views/hyrax/homepage/_home_content.html.erb

update to fix mismatch p tag

---

app/views/_user_util_links.html.erb
app/views/hyrax/homepage/_home_content.html.erb

Ticket #2188: Commit to fix tabindex on sign up and thumbnails

---

app/assets/javascripts/blacklight/ajax_modal.js
app/assets/javascripts/hydra-editor/field_manager.es6
app/assets/javascripts/oregon_digital/collections/explore_collections_modals.js
app/assets/javascripts/oregon_digital/editor.js
app/views/_user_util_links.html.erb
app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb
app/views/hyrax/homepage/_login_modal.html.erb
app/views/layouts/hyrax.html.erb
app/views/oregon_digital/dashboard/collections/_form_for_create_collection.html.erb
app/views/oregon_digital/explore_collections/_form_for_delete_collection.html.erb
app/views/oregon_digital/explore_collections/_form_for_edit_collection.html.erb
app/views/oregon_digital/explore_collections/_form_for_export_collection.html.erb
app/views/shared/_select_work_type_modal.html.erb

Fixes #1949 
@straleyb I highly recommend reviewing this commit-by-commit, they should loosely line up with the points in #1949

Collection creation modal improvements + Form improvements

---

app/assets/javascripts/blacklight/ajax_modal.js
app/views/catalog/_facet_limit.html.erb

Change data-href for BL ajax and remove bootstrap ajax

---

app/views/catalog/_facet_limit.html.erb

Sort facet items by selected and count

---

lib/hyrax/controlled_vocabularies/location.rb

if parents, always fetch

---

app/assets/javascripts/hyrax/collections/editor.es6
app/forms/oregon_digital/forms/collection_form.rb
app/models/collection_representative.rb
app/presenters/oregon_digital/collection_presenter.rb
app/views/hyrax/collections/show.html.erb
app/views/hyrax/dashboard/collections/_form_branding.html.erb
config/initializers/hacks/hyrax_collections_controller.rb
config/locales/hyrax.en.yml
db/migrate/20220325221318_create_collection_representatives.rb
db/schema.rb
spec/factories/collection_representatives.rb
spec/models/collection_representative_spec.rb
spec/presenters/oregon_digital/collection_presenter_spec.rb

Add collection representative model and hook to collection form

---

app/views/hyrax/dashboard/_sidebar.html.erb

Ticket #1844: Commit to fix back button and css on dashboard sidebar

---

app/assets/javascripts/blacklight/ajax_modal.js
app/views/catalog/_facet_pagination.html.erb
app/views/hyrax/my/_facet_limit.html.erb
app/views/hyrax/my/_facet_pagination.html.erb

Fix facet modals in more locations

---

config/initializers/hacks/blacklight_advanced_controller.rb
config/initializers/hacks/hyrax_ability_helper.rb
config/initializers/hacks/hyrax_collections_controller.rb
config/initializers/hacks/hyrax_collections_controller_behavior.rb
config/initializers/hacks/hyrax_collections_members_controller.rb
config/initializers/hacks/hyrax_create_with_remote_files_actor.rb
config/initializers/hacks/hyrax_create_with_remote_files_ordered_members_actor.rb
config/initializers/hacks/hyrax_file_set_edit_form.rb
config/initializers/hacks/iiif_manifest_canvas_builder.rb
config/initializers/hacks/libhoney.rb
config/initializers/hacks/omniauth_strategies_saml.rb

Based on this answer: https://stackoverflow.com/questions/8895103/how-can-i-keep-my-initializer-configuration-from-being-lost-in-development-mode

Make hacks run every page load in dev

---

lib/oregon_digital/controlled_vocabularies/scientific.rb
spec/oregon_digital/controlled_vocabularies/scientific_spec.rb

fixes #2246 
At first I was just going to add a bit more logic and use super if in_triplestore?
but that results in a second call to triplestore

stash graph

---

lib/oregon_digital/controlled_vocabularies/vocabularies/itis.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/ubio.rb

fixes #2128
fixes #2153
missing module, not class

missing module

---

Gemfile
Gemfile.lock

Upgrade to the latest `honeycomb-beeline` and `libhoney`

update honeycomb beeline and libhoney

---

app/views/hyrax/collections/_collection_description.erb
app/views/hyrax/collections/show.html.erb

Prevent render of collection description if there is no description

---

app/assets/javascripts/oregon_digital/collections/collection_submit.js
app/assets/stylesheets/oregon_digital/collections/show.scss
app/views/hyrax/collections/show.html.erb

Spacing on representative images

---

app/indexers/generic_indexer.rb
app/views/hyrax/collections/_advanced_search_form.html.erb
app/views/hyrax/collections/_search_form.html.erb
app/views/hyrax/collections/show.html.erb

Switch collection index field searched on collection landing page based on if collection is a user collection or not
Fixes #2274

Add indexing field for which user collections a work is in

---

app/views/hyrax/collections/_showcase_tile.html.erb
app/views/hyrax/collections/show.html.erb
config/initializers/hacks/hyrax_collections_controller.rb
config/initializers/hacks/hyrax_collections_members_controller.rb

Add default representative images and fill out images as works are added

---

app/services/oregon_digital/file_set_streamer.rb

Choose the correct standard derivative type and skip odd extra files in full size filesets

---

app/views/hyrax/dashboard/collections/_form.html.erb

Restrict my collection edit for to OSU/UO accounts

---

app/services/concerns/oregon_digital/streaming_download_behavior.rb
app/services/oregon_digital/collection_streamer.rb
app/services/oregon_digital/file_set_streamer.rb

Better export derivatives and full size files based on derivative status
Fixes #1341

Refactor fileset and collection streaming into behavior

---

app/models/ability.rb
app/views/hyrax/collections/_show_document_list.html.erb
app/views/hyrax/collections/_show_document_list_row.html.erb
app/views/hyrax/collections/show.html.erb

Show removable works on my collection landing page

---

app/controllers/concerns/oregon_digital/iiif_manifest_controller_behavior.rb
app/presenters/hyrax/generic_presenter.rb
app/presenters/oregon_digital/iiif_presenter.rb
app/presenters/oregon_digital/jp2_presenter.rb
app/views/hyrax/base/show.html.erb
config/initializers/hacks/iiif_manifest_canvas_builder.rb
package.json
spec/controllers/concerns/oregon_digital/iiif_manifest_controller_behavior_spec.rb
spec/presenters/hyrax/generic_presenter_spec.rb
spec/presenters/oregon_digital/jp2_presenter_spec.rb
yarn.lock

This gets Images and PDFs back up and running for IIIF Manifest V3 spec

Image and PDF ready for IIIF V3

---

app/indexers/generic_indexer.rb
app/views/hyrax/collections/_advanced_search_form.html.erb
app/views/hyrax/collections/_search_form.html.erb
app/views/hyrax/collections/show.html.erb
config/initializers/hacks/hyrax_collections_controller.rb

Fixes #1248
Fixes #2275 
Fixes #2274

My collection item removal and improved search

---

app/models/audio.rb
app/models/document.rb
app/models/generic.rb
app/models/image.rb
app/models/video.rb

first step for https://github.com/OregonDigital/OD2/issues/2199

comments out include edtf

---

app/forms/oregon_digital/forms/collection_form.rb
app/workers/fetch_graph_worker.rb

Require resource type on collection form and update AF resource index after fetching

---

config/locales/generic.en.yml

Add value for institution_label

---

app/assets/stylesheets/oregon_digital/_home-page.scss
app/assets/stylesheets/oregon_digital/_search.scss
app/views/catalog/_document.html.erb
app/views/catalog/_thumbnail_list_collection.html.erb
app/views/hyrax/base/_index_gallery.html.erb
app/views/hyrax/homepage/_home_content.html.erb

Improve thumbnails on compound object, search, and homepage

---

app/assets/stylesheets/oregon_digital/_search.scss
app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
app/views/catalog/_index_list_default.html.erb

Order and add CSS to compound object search results

---

config/authorities/download.yml
lib/tasks/oregon_digital/create_full_metadata_work.rake

Update download authority values.

---

app/views/catalog/_facet_pagination.html.erb
app/views/hyrax/my/_facet_pagination.html.erb

Set data-href correctly on facet pagination

---

app/services/concerns/oregon_digital/streaming_download_behavior.rb

Fix PDF standard download case

---

app/assets/stylesheets/oregon_digital/_viewer.scss
config/uv/uv-config.json
config/uv/uv.html

UV CSS and html/config updates

---

config/uv/uv.html
package.json
yarn.lock

v4 fixes the full screen issue introduced (for us) in v3.1.5

Update UV to v4.0.0

---

Gemfile.lock
config/initializers/migrator/collections.yml
config/initializers/migrator/crosswalk_admin_sets.yml
config/initializers/migrator/crosswalk_overrides.yml
config/initializers/migrator/fields_map.yml

updates migrator to get fixes for issues 330 and 324.
Also updates files in config/initializers/migrator:
fixes https://github.com/OregonDigital/hyrax-migrator/issues/318
fixes https://github.com/OregonDigital/hyrax-migrator/issues/319
fixes https://github.com/OregonDigital/hyrax-migrator/issues/296

Update migrator 8b5e5dd

---

app/views/catalog/_index_list_default.html.erb

Remove compound object search icon

---

app/assets/stylesheets/oregon_digital/_home-page.scss
app/views/hyrax/homepage/_home_content.html.erb
app/views/layouts/homepage.html.erb

Homepage mobile overhaul

---

app/indexers/generic_indexer.rb
config/initializers/migrator/crosswalk_overrides.yml

fixes #2333 
also fixes a typo.

Combined topic

---

app/views/hyrax/base/_form_relationships.html.erb

Set Admin Set value to empty on new form

---

app/controllers/catalog_controller.rb
app/controllers/oregon_digital/explore_collections_controller.rb
app/models/ability.rb
app/models/concerns/oregon_digital/ability/collection_ability.rb
app/models/concerns/oregon_digital/ability/work_create_ability.rb
app/models/concerns/oregon_digital/ability/work_delete_ability.rb
app/models/concerns/oregon_digital/ability/work_download_ability.rb
app/models/concerns/oregon_digital/ability/work_edit_ability.rb
app/models/concerns/oregon_digital/ability/work_show_ability.rb
app/models/user.rb
app/views/hyrax/dashboard/collections/_form.html.erb

`admin_permission_roles` and others need to be a class method off `Ability` in order to be used in the `User` class.

Fix viewable work count and other misadventures

---

app/controllers/catalog_controller.rb
app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
config/authorities/download.yml
lib/tasks/oregon_digital/create_full_metadata_work.rake

Move full_size_download_allowed to 0/1 values

---

app/views/records/edit_fields/_modal_description.html.erb
config/initializers/hacks/hyrax_collections_controller.rb

Fake collection description as multivalue & add nil check to representative guard clause

---

app/jobs/bulk_approve_job.rb
spec/jobs/bulk_approve_job_spec.rb

fixes https://github.com/OregonDigital/hyrax-migrator/issues/290

bulk approve item

---

app/views/oregon_digital/explore_collections/_form_for_export_collection.html.erb

Hide export modal on export click

---

app/indexers/oregon_digital/deep_indexing_service.rb

Allow collections through fetch_external fileset check

---

lib/oregon_digital/derivatives/video/video_processor.rb

Add audio bitrate checks to video processor

---

app/views/hyrax/collections/_advanced_search_form.html.erb
app/views/hyrax/collections/show.html.erb

Remove metadata link and footer if there's no metadata to display
Second part of Sharing step for #1407

Remove facet header if no facets are present

---

app/services/oregon_digital/collection_streamer.rb

Add child work metadata to collection export

---

app/assets/stylesheets/oregon_digital/_work-show.scss
app/assets/stylesheets/oregon_digital/explore_collections/_masonry_view.scss
app/views/hyrax/collections/_advanced_search_form.html.erb
app/views/oregon_digital/explore_collections/_document_masonry.html.erb

Resize explore collection thumbs

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
app/helpers/oregon_digital/hyrax_helper_behavior.rb

Convert collection ids in facet to collection title/label

---

app/models/collection.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/hyrax_migrator.rb

fixes #2387 
(also adds label exists verifier to list of default verifiers in the migrator config)

set reindex_extent for colls

---

.circleci/config.yml
Gemfile.lock
app/assets/javascripts/oregon_digital/collections/explore_collections_modals.js
app/views/oregon_digital/dashboard/collections/_form_for_create_collection.html.erb
app/views/oregon_digital/explore_collections/_collection_edit_data.erb
app/views/oregon_digital/explore_collections/_form_for_edit_collection.html.erb
app/views/oregon_digital/explore_collections/index.html.erb
app/views/records/edit_fields/_modal_title.erb

Pre-bake collection edit form data & make title/desc single value

---

app/assets/javascripts/oregon_digital/collections/explore_collections_modals.js
app/views/hyrax/dashboard/collections/_button_remove_from_collection.html.erb

Improve my collection item removal message

---

config/initializers/migrator/crosswalk_overrides.yml

fixing typo, view_date should be view

fix property

---

app/controllers/concerns/oregon_digital/download_controller_behavior.rb
app/models/concerns/oregon_digital/collection_behavior.rb
app/models/concerns/oregon_digital/work_behavior.rb
app/services/concerns/oregon_digital/streaming_download_behavior.rb
app/services/oregon_digital/collection_streamer.rb
app/services/oregon_digital/file_set_streamer.rb
spec/models/collection_spec.rb
spec/models/generic_spec.rb
spec/services/oregon_digital/collection_streamer_spec.rb

CSV metadata key/value alignment

---

app/views/advanced/_advanced_search_facets_as_select.html.erb

Use blacklight configured helper_method for advanced search facet fields

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
app/indexers/generic_indexer.rb
config/solr/conf/schema.xml

Fixes #1652 
The solr config needs to be updated on staging/prod

Add sortable title and date solr fields and search sort options

---

app/models/solr_document.rb
lib/oregon_digital/qualified_dublin_core.rb

Fix Qualified Dublin Core module namespace collision with OregonDigital::Document

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb

Fix blacklight sorting title_field

---

app/views/catalog/_document_gallery.html.erb
app/views/catalog/_index_list_default.html.erb
app/views/kaminari/blacklight/_paginator.html.erb

Move child pagination to bottom in mobile view

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
app/indexers/generic_indexer.rb

Add searchable collection field

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb

Add scientific name to facet list

---

app/models/user.rb
app/views/hyrax/homepage/_login_modal.html.erb

User sign up fixes

---

app/models/search_builder.rb

This removes a method that allows for AND/OR statements in ordinary search.

Removes broken processor chain piece.

---

app/controllers/concerns/oregon_digital/works_controller_behavior.rb
app/jobs/oregon_digital/work_permission_change_job.rb
spec/jobs/oregon_digital/work_permission_change_job_spec.rb

Work on permission changing part of #1709

Add work logging for visibility updates

---

app/views/_user_util_links.html.erb
app/views/hyrax/dashboard/sidebar/_configuration.html.erb

Enables users to get where they need for role management and depositing/reviewing.

Enables admin to reach roles from dashboard. Adds dashboard to dropdown for depositors/reviews

---

app/models/concerns/oregon_digital/generic_metadata.rb
config/initializers/migrator/crosswalk.yml

fix typo in predicate, brought in from OD2 map

fix typo wait for confirmation

---

app/views/records/edit_fields/_modal_title.erb

Fixes #1407 - Task 1
Task 4 was fixed by #2428

Make title required for my collection form

---

config/locales/oregon_digital.en.yml

Update email in use message

---

app/controllers/concerns/oregon_digital/works_controller_behavior.rb
app/jobs/attach_child_to_work_event_job.rb
app/jobs/detach_child_from_work_event_job.rb
app/jobs/oregon_digital/permission_change_event_job.rb
app/jobs/oregon_digital/permission_change_propagation_event_job.rb
app/jobs/oregon_digital/permission_change_propagation_job.rb
app/jobs/visibility_copy_job.rb
config/initializers/hacks/hyrax_actors_attach_members_actor_hack.rb
config/initializers/hacks/hyrax_file_sets_controller.rb
spec/jobs/oregon_digital/permission_change_event_job_spec.rb
spec/jobs/oregon_digital/permission_change_propagation_event_job_spec.rb
spec/jobs/oregon_digital/permission_change_propagation_job_spec.rb

Finishes permission changing event logging for #1709

FileSet permission event logging

---

config/initializers/migrator/crosswalk_overrides.yml
config/initializers/migrator/fields_map.yml

fixes https://github.com/OregonDigital/hyrax-migrator/issues/348

map old rightsHolder pred

---

app/models/solr_document.rb
app/presenters/hyrax/file_set_presenter.rb
app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb

Prevent autosearching when no extracted/ocr text available

---

Gemfile.lock

brings addition to metadata profiler 
https://github.com/OregonDigital/hyrax-migrator/commit/87173608ae1def27fe9f97bc46e10cd4f72c6a3a
Also, not sure why oai, blacklight-oai is getting added here, but am told it's ok!

update migrator 8717360

---

app/models/user.rb
app/views/devise/shared/_error_messages.html.erb

Remove password requirement for institutional authentication & account creation

---

app/controllers/hyrax/dashboard/profiles_controller.rb
app/jobs/user_edit_profile_event_job.rb
app/models/ability.rb
app/views/hyrax/dashboard/sidebar/_configuration.html.erb

Enables user information to be edited by an admin

updates so users can edit other people's names

---

app/indexers/oregon_digital/deep_indexing_service.rb
spec/indexers/oregon_digital/deep_indexing_service_spec.rb

do not block rdf for missing label

---

app/views/_user_util_links.html.erb
app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb
app/views/hyrax/homepage/_home_content.html.erb
app/views/oregon_digital/explore_collections/_explore_tabs.html.erb
app/views/users/mailer/confirmation_instructions.html.erb
config/routes.rb

Update route and internal routing for explore collections

---

app/views/users/mailer/reset_password_instructions.html.erb

updates email to reflect MVP

---

app/assets/javascripts/hyrax/search.js
app/controllers/oregon_digital/about_controller.rb
app/views/oregon_digital/about/about.html.erb
app/views/oregon_digital/about/copyright.html.erb
app/views/oregon_digital/about/harmful.html.erb
app/views/oregon_digital/about/mission.html.erb
app/views/oregon_digital/about/osu.html.erb
app/views/oregon_digital/about/privacy.html.erb
app/views/oregon_digital/about/takedown.html.erb
app/views/oregon_digital/about/terms.html.erb
app/views/oregon_digital/about/uo.html.erb
app/views/oregon_digital/about/use.html.erb
config/routes.rb

About pages skeletons

---

app/views/oregon_digital/about/_sidebar.html.erb
app/views/oregon_digital/about/harmful.html.erb
app/views/oregon_digital/about/takedown.html.erb
app/views/oregon_digital/about/terms.html.erb
config/routes.rb

Terms, Harmful, and Take-down pages for #2101

Terms, Harmful, and Takedown pages

---

app/views/_user_util_links.html.erb

Add user email to user util dropdown

---

app/forms/oregon_digital/forms/collection_form.rb
spec/forms/oregon_digital/forms/collection_form_spec.rb

Reverts OregonDigital/OD2#2467

Revert "add id to collection for custom collection id"

---

config/initializers/hacks/hyrax_collections_members_controller.rb

Prevent double representative images

---

app/helpers/oregon_digital/hyrax_helper_behavior.rb
app/presenters/hyrax/file_set_presenter.rb
app/presenters/hyrax/generic_presenter.rb
app/views/hyrax/base/_work_contact_form.html.erb
app/views/hyrax/base/show.html.erb
app/views/hyrax/contact_form/new.html.erb
app/views/hyrax/file_sets/show.html.erb

Remove bad page titles

---

app/controllers/concerns/hyrax/breadcrumbs_for_collections.rb
config/locales/hyrax.en.yml

Change collection show page to include explore collection & edit pages

---

app/controllers/oregon_digital/explore_collections_controller.rb

Use ActiveFedora lookup to get accurate total viewable item count

---

app/views/_user_util_links.html.erb

Move user email above dashboard for admin users

---

app/controllers/oregon_digital/explore_collections_controller.rb

Fix solr field group for total_viewable_items

---

app/models/concerns/oregon_digital/image_metadata.rb
app/models/concerns/oregon_digital/video_metadata.rb

Changes locations to geographics header for Image/Video

---

app/views/catalog/_sort_and_per_page.html.erb
app/views/hyrax/admin/workflows/_sort_and_per_page.html.erb
app/views/hyrax/dashboard/collections/_form_for_select_collection.html.erb
config/locales/hyrax.en.yml

Transition 'save to' to 'add to'

---

app/controllers/oregon_digital/explore_collections_controller.rb

Fixes #2144 Where logged out users did not have roles and threw a nil to array conversion error

Only add group visibilities to logged in users

---

app/assets/stylesheets/oregon_digital/_sign_up.scss
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

Fixes #265 
Adds privacy policy link to all devise pages (signup/login/password)
Starts the wireframe implementation for devise pages. Still to do is the flex box of inputs/submission button & styling on the input boxes

Devise page updates

---

app/controllers/oregon_digital/iiif_manifest_v2_controller.rb
config/routes.rb
spec/controllers/oregon_digital/iiif_manifest_v2_controller_spec.rb

Iiif v2 manifest

---

app/controllers/concerns/hyrax/dashboard_authorization.rb
config/initializers/hacks/hyrax_dashboard_authorization.rb
spec/controllers/admin/oregon_digital/collection_types_controller_spec.rb

Route unprivileged users from dashboard to homepage

---

app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/sessions_controller.rb

Redirect users to previous page on log in

---

app/views/hyrax/collections/show.html.erb

Remove anchor from view all collection link

---

app/controllers/oregon_digital/iiif_manifest_v2_controller.rb
app/presenters/oregon_digital/iiif_v2_presenter.rb
app/presenters/oregon_digital/jp2_v2_presenter.rb
spec/controllers/oregon_digital/iiif_manifest_v2_controller_spec.rb
spec/presenters/oregon_digital/iiif_v2_presenter_spec.rb
spec/presenters/oregon_digital/jp2_v2_presenter_spec.rb

see #2517
Just adding a reverted controller wasn't going to be enough, also needed v2 presenters. Also added thumbnails.

add v2 presenters

---

app/views/catalog/_index_list_default.html.erb

Add line break after collection description in search results

---

config/initializers/migrator/crosswalk_admin_sets.yml

Add chuck-williams

---

config/initializers/_hyrax.rb

Remove format_label and add use_restrictions to manifest metadata

---

app/controllers/application_controller.rb

Redirect non-institution users too

---

app/controllers/oregon_digital/explore_collections_controller.rb

Add check for suppression

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/oregon_digital/cookie_consent.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/oregon_digital/_footer.scss

Add cookie consent footer

---

app/models/solr_document.rb
app/presenters/oregon_digital/iiif_presenter.rb
app/presenters/oregon_digital/iiif_v2_presenter.rb
app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
config/uv/uv-config.json
config/uv/uv.html
spec/presenters/oregon_digital/iiif_presenter_spec.rb
spec/presenters/oregon_digital/iiif_v2_presenter_spec.rb

Fixes #1426 
Fixes #1537 
Fixes #1646

Fix UV page labels & search box

---

app/controllers/application_controller.rb
app/controllers/concerns/oregon_digital/iiif_manifest_controller_behavior.rb
app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb

Prevent sign in redirecting to thumbnail or manifest

---

app/views/hyrax/dashboard/collections/_list_collections.html.erb

Fix collection titles in wrong column on dashboard

---

app/presenters/hyrax/generic_presenter.rb
lib/oregon_digital/triplestore.rb

Handle case where URI can not be fetched from cache or source

---

app/controllers/concerns/oregon_digital/iiif_manifest_controller_behavior.rb

Ensure json redirect for users and admins

---

app/views/hyrax/collections/show.html.erb

Show lesser of viewable and unsuppressed work counts

---

app/models/concerns/oregon_digital/generic_metadata.rb
app/models/concerns/oregon_digital/image_metadata.rb

Move view metadata from image to generic

---

app/assets/javascripts/oregon_digital/toggle_login_footer.js
app/assets/stylesheets/oregon_digital/_sign_up.scss
app/views/_user_util_links.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/hyrax/homepage/_login_modal.html.erb
app/views/layouts/hyrax.html.erb
app/views/layouts/hyrax/dashboard.html.erb

Devise wireframes

---

app/views/advanced/_advanced_search_facets_as_select.html.erb
app/views/hyrax/collections/_advanced_search_facets_as_select.html.erb

Fixes #2083
I left commit e149da384cd1ff0fc1da86fc346ecf6d2ff9b1e0 in so we have a working version with type ahead, in case we need it for whatever reason

Date range facet for advanced search

---

app/models/solr_document.rb
app/presenters/hyrax/generic_presenter.rb

Fix non_user_collections display on work show page

---

lib/oregon_digital/controlled_vocabularies/resource.rb

Override #rdf_label to acquire all labels and select for english

---

app/forms/oregon_digital/forms/collection_form.rb
spec/forms/oregon_digital/forms/collection_form_spec.rb

On create the id can be customized, on update id is removed from form. Ids cannot be updated.
ID is required

uses dynamic form generation for creation/update of collection w/ custom id

---

app/assets/stylesheets/oregon_digital/_sign_up.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

Move login input above shared links

---

app/assets/stylesheets/oregon_digital/_sign_up.scss
app/assets/stylesheets/oregon_digital/explore_collections/_masonry_view.scss
app/views/devise/registrations/new.html.erb

Line break char minimum

---

app/assets/stylesheets/oregon_digital/utils.scss
app/views/advanced/_advanced_search_facets_as_select.html.erb
app/views/hyrax/collections/_advanced_search_facets_as_select.html.erb

Change date separator to 'to'

---

app/models/concerns/oregon_digital/generic_metadata.rb
app/models/concerns/oregon_digital/image_metadata.rb

Move view ordered_term from image to generic

---

app/assets/stylesheets/oregon_digital/bootstrap/_modals.scss
app/views/hyrax/homepage/_login_modal.html.erb

Login modal wireframe

---

app/assets/html/401.html.haml

Add sign up and sign in links to 401

---

app/views/devise/registrations/new.html.erb
config/locales/hyrax.en.yml

Password confirmation => Confirm password

---

app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/_social_media.html.erb

updates position and size of text box and share buttons

---

app/views/devise/registrations/new.html.erb

Make sure new password input and label match

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
app/models/oai_set.rb
app/models/solr_document.rb

OAI configuration

---

app/assets/stylesheets/oregon_digital/_search.scss
app/assets/stylesheets/oregon_digital/fonts.scss
app/assets/stylesheets/oregon_digital/utils.scss
app/views/catalog/_zero_results.html.erb
app/views/catalog/index.html.erb
app/views/shared/_colored_divider.html.erb

No results page

---

app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/_social_media.html.erb

updates layout to be more customized and lined up

---

app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb

Include all_fields (from adv search) in auto-search

---

app/controllers/concerns/oregon_digital/iiif_manifest_controller_behavior.rb
app/presenters/oregon_digital/iiif_presenter.rb
spec/controllers/concerns/oregon_digital/iiif_manifest_controller_behavior_spec.rb

I hope this fixes #2616 
I think the issue here is the 200+ FileSet iterations, multiple times. They should at least be faster with SolrDocs, if that's not enough I'll try tuning the loops

Try using SolrDocuments to build IIIFmanifest

---

app/assets/stylesheets/oregon_digital/bootstrap/_modals.scss
app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
app/views/hyrax/homepage/_login_modal.html.erb

Login Modal improvements

---

app/assets/javascripts/oregon_digital/toggle_login_footer.js

Add optional chaining to login modal setup

---

app/assets/javascripts/oregon_digital/toggle_login_footer.js

Because Uglifier gem doesn't like #2624

Uglifier doesn't like > ES6

---

app/assets/javascripts/oregon_digital/collections/masonry.js
app/assets/stylesheets/oregon_digital/_header.scss
app/assets/stylesheets/oregon_digital/_search.scss
config/locales/blacklight.en.yml

Explore collection masonry improvements

---

app/assets/stylesheets/oregon_digital/_footer.scss
app/views/hyrax/homepage/_home_content.html.erb

Fixes footer a11y test failures

Use dark-grey in footer for contrast

---

app/presenters/oregon_digital/iiif_presenter.rb
app/presenters/oregon_digital/iiif_v2_presenter.rb

Switch Collection loads to SolrDocument loads

---

lib/oregon_digital/controlled_vocabularies/vocabularies/getty_base.rb

Search all Getty labels specifically for English
Fixes #2429

Improve getty label fetching for QA

---

app/indexers/generic_indexer.rb
app/models/solr_document.rb
app/presenters/hyrax/generic_presenter.rb
app/views/hyrax/base/_attribute_rows.html.erb
lib/oregon_digital/fedora_finder.rb

Remove OAI sets from collection list on work show page

---

app/controllers/oregon_digital/iiif_manifest_v2_controller.rb
app/presenters/oregon_digital/iiif_presenter.rb
app/presenters/oregon_digital/iiif_v2_presenter.rb
spec/controllers/oregon_digital/iiif_manifest_v2_controller_spec.rb

Cache collection titles in iiif presenter

---

app/presenters/oregon_digital/iiif_presenter.rb
app/presenters/oregon_digital/iiif_v2_presenter.rb

Try to batch solr requests together & prevent many queries

---

app/assets/stylesheets/oregon_digital/_advanced.scss
app/assets/stylesheets/oregon_digital/_buttons.scss
app/assets/stylesheets/oregon_digital/_contact.scss
app/assets/stylesheets/oregon_digital/_search.scss
app/assets/stylesheets/oregon_digital/_work-show.scss
app/assets/stylesheets/oregon_digital/collections/show.scss
app/presenters/hyrax/generic_presenter.rb
app/views/advanced/_advanced_search_facets_as_select.html.erb
app/views/catalog/_index_gallery.html.erb
app/views/catalog/_index_masonry.html.erb
app/views/hyrax/base/_index_gallery.html.erb
app/views/hyrax/base/_show_collection_header.html.erb
app/views/hyrax/base/_work_contact_form.html.erb
app/views/hyrax/base/show.html.erb
app/views/hyrax/collections/_showcase_tile.html.erb
app/views/hyrax/contact_form/new.html.erb
app/views/oregon_digital/explore_collections/_index_masonry.html.erb

Work show page wireframe improvements

---

app/assets/stylesheets/oregon_digital/_buttons.scss
app/assets/stylesheets/oregon_digital/_header.scss
app/assets/stylesheets/oregon_digital/_home-page.scss
app/views/_user_util_links.html.erb

Homepage wireframe work

---

app/controllers/concerns/hyrax/dashboard_authorization.rb

Allow users to change visibility of their collections

---

app/presenters/oregon_digital/jp2_v2_presenter.rb
spec/presenters/oregon_digital/jp2_v2_presenter_spec.rb

tweak image paths for size

---

app/assets/stylesheets/oregon_digital/_work-show.scss
app/assets/stylesheets/oregon_digital/collections/show.scss
app/views/hyrax/collections/show.html.erb

View text changes and Safari dl fix

---

app/assets/javascripts/oregon_digital/toggle_copied.js
app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/_social_media.html.erb
app/views/oregon_digital/explore_collections/_actions_list.html.erb
app/views/oregon_digital/explore_collections/_actions_masonry.html.erb
app/views/shared/_fileset_collection_social_media.html.erb

Align copy button and copy input box plus fix copy button tooltips

---

app/assets/stylesheets/oregon_digital/_advanced.scss
app/views/advanced/_advanced_search_help.html.erb
app/views/advanced/index.html.erb

Move search tips below search button

---

app/assets/stylesheets/oregon_digital/collections/show.scss

Increase colored divider gap

---

app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/_work_contact_form.html.erb

Work show page contact form labels and button

---

app/assets/stylesheets/oregon_digital/_footer.scss
app/assets/stylesheets/oregon_digital/_header.scss
app/views/shared/_footer.html.erb

Header dropdown, Footer layout

---

app/indexers/concerns/oregon_digital/indexing_dates_behavior.rb

Remove acquisition_date from date_combined_fields

---

app/views/devise/registrations/new.html.erb

Updates view to include why sign up

---

app/services/oregon_digital/hocr_derivative_service.rb
app/workers/re_extract_text_worker.rb
lib/tasks/oregon_digital/recreate_text_derivatives.rake

Needs testing for text extraction, hOCR works

Create a new rake task/job to re-extract/ocr all pdfs

---

config/uv/uv-config.json

Default UV view to index for multiple children works

---

app/views/_logo.html.erb

Pluralize collections

---

app/assets/stylesheets/oregon_digital/_work-show.scss

Remove inline-block display from metadata

---

app/indexers/oregon_digital/collection_indexer.rb
app/search_builders/oregon_digital/non_user_collections_search_builder.rb
app/views/oregon_digital/explore_collections/_sort_widget.html.erb

Add sorting to explore collections page

---

lib/hyrax/controlled_vocabularies/location.rb

Rewrite location county collapsing without regex and supporting locations before counties

---

app/presenters/oregon_digital/iiif_v2_presenter.rb

v2 manifest_url

---

Gemfile
Gemfile.lock
app/models/concerns/bulkrax/has_local_processing.rb
config/initializers/bulkrax.rb
db/schema.rb

bulkrax v2

---

app/assets/stylesheets/print.scss

Print CSS for masonry items and homepage

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb

Up default search amount to 20

---

app/views/hyrax/users/_user.html.erb
app/views/hyrax/users/_user_roles.html.erb

No ticket, this has just been really annoying to me

Add roles to user show page

---

app/controllers/oregon_digital/explore_collections_controller.rb

Remove some explore collection sort options

---

app/controllers/concerns/hyrax/dashboard_authorization.rb
config/initializers/hacks/hyrax_dashboard_authorization.rb

Simplify My Shelf permissions exceptions to admin or operating on a user collection

---

app/controllers/oregon_digital/explore_collections_controller.rb

Remove leading article from explore collection sort

---

app/presenters/oregon_digital/mp3_presenter.rb

Handle nil case for audio playback duration

Fix audio UV display issue

---

Dockerfile
app/presenters/oregon_digital/iiif_v2_presenter.rb
config/initializers/sidekiq.rb
config/sidekiq.yml

noscrub metadata

---

app/views/oregon_digital/about/about.html.erb

Update launch date on about page

---

config/initializers/hacks/hyrax_downloads_controller_hack.rb

Always allow thumbnails to be downloaded/viewed

---

config/solr/conf/stopwords.txt

Add stopwords to solr config

---

app/views/oregon_digital/about/privacy.html.erb
app/views/oregon_digital/about/takedown.html.erb

Fix typos in about pages

---

app/assets/stylesheets/print.scss

Shrink masonry icons and align to rows

---

app/controllers/concerns/hyrax/dashboard_authorization.rb

Add missing case for deleting my collection/work

---

app/indexers/concerns/oregon_digital/strips_stopwords.rb
app/indexers/generic_indexer.rb
app/indexers/oregon_digital/collection_indexer.rb

Strip solr stopwords from title_ssort before sending to solr

---

app/assets/stylesheets/oregon_digital/forms.scss
app/views/oregon_digital/oembeds/edit.html.erb
config/locales/oregon_digital.en.yml

Only show oembed error message if there are errors

---

app/models/user.rb
config/roles.yml
spec/models/ability_spec.rb

Add community_user role to non-institutional user

---

app/controllers/concerns/oregon_digital/works_controller_behavior.rb
app/controllers/hyrax/audios_controller.rb
app/controllers/hyrax/documents_controller.rb
app/controllers/hyrax/generics_controller.rb
app/controllers/hyrax/images_controller.rb
app/controllers/hyrax/videos_controller.rb

Redirect users that go to a valid work pid but the wrong worktype

---

public/robots.txt

A very basic robots.txt

---

app/views/_user_util_links.html.erb

Direct user to actual user page

---

config/locales/hyrax.en.yml

Remove beta tag

---

app/assets/stylesheets/oregon_digital/_search.scss
app/views/catalog/_index_list_default.html.erb
app/views/shared/_citations.html.erb

Fixes for #2477 
Does not include `show more facets`

Search page wireframe adjustments & opengraph metadata

---

app/assets/stylesheets/oregon_digital/_home-page.scss
app/views/hyrax/homepage/_announcement.html.erb

Color and formatting for homepage banner

---

app/views/hyrax/homepage/_home_content.html.erb

We only need the first 3 with something in the `file_set_ids_ssim` field

Don't load every document in the collection

---

config/authorities/languages.yml

Add additional language codes.

---

app/controllers/concerns/oregon_digital/iiif_manifest_controller_behavior.rb
app/controllers/oregon_digital/iiif_manifest_v2_controller.rb
config/environments/test.rb
spec/controllers/concerns/oregon_digital/iiif_manifest_controller_behavior_spec.rb
spec/controllers/oregon_digital/iiif_manifest_v2_controller_spec.rb

Cache the v3 and v2 IIIFManifest

---

app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb

Remove quotes and strip string from catalog search query

---

app/views/hyrax/collections/show.html.erb

Prevent share link from displaying on unshared user collection

---

app/controllers/concerns/oregon_digital/iiif_manifest_controller_behavior.rb
app/controllers/oregon_digital/iiif_manifest_v2_controller.rb

Cache v3 and v2 manifests in different keys

---

.rubocop.yml
app/indexers/generic_indexer.rb

Try to grab an existing date from date field
Fixes #2802 after a reindex

Attempt regular date parsing, then edtf parsing

---

app/controllers/concerns/hyrax/breadcrumbs_for_collections.rb

Add show path to collection edit form breadcrumbs to match work edit form

---

app/indexers/generic_indexer.rb

Make sure date_dtsi is a datetime

---

config/robots.production.txt

Allow crawling of thumbnails in robots.txt

---

app/assets/stylesheets/oregon_digital/_work-show.scss

Clean up mobile view of work show tabs

---

app/authorities/qa/authorities/collections.rb

Add wild card to catalog QA search

---

config/initializers/bulkrax.rb
spec/factories/bulkrax_importers.rb
spec/fixtures/pna99999_1.csv
spec/models/bulkrax/csv_entry_spec.rb

fixes #2844
also finally getting around to starting a spec.

use bagit mapping for csv

---

config/uv/uv-config.json

enable iframe code button

---

config/initializers/bulkrax.rb
spec/factories/bulkrax_importers.rb
spec/fixtures/pna99999_1.csv
spec/models/bulkrax/csv_entry_spec.rb

Bulkrax multiples

---

.circleci/config.yml
Gemfile
Gemfile.lock
app/models/concerns/bulkrax/has_local_processing.rb
config/initializers/bulkrax.rb

Bulkrax v3

---

config/initializers/bulkrax.rb

configure relationships join

---

app/assets/stylesheets/oregon_digital/_no_results.scss
app/views/catalog/_zero_results.html.erb
config/locales/blacklight.en.yml

`In Progress`: Add in couple new messages on `No Results Found`.

Clean up the 'No Results Found'

---

app/indexers/oregon_digital/deep_indexing_service.rb
spec/workers/fetch_graph_worker_spec.rb

remove deep_indexing block

---

app/views/catalog/_constraints.html.erb

Revise search result tally for searches with fewer than max displayed number of results

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
config/locales/generic.en.yml

Add in the facet of `local collection name` where display local collection we have as a search filter option to narrow down more items.

Add in facet with local collection

---

app/views/hyrax/homepage/_home_content.html.erb

Uhhhh.... Yeah. Maybe we do this instead of spending 40sec asking Fedora for a 14k object collection
@straleyb

User solr for homepage collection lookup

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb

Add in a fix to `limit: 5` Local Collection Name to the facet filter on OD2.

Add in limit to the new facet

---

config/initializers/bulkrax.rb
spec/factories/bulkrax_exporters.rb
spec/models/bulkrax/csv_entry_spec.rb

check for empties

---

app/presenters/oregon_digital/iiif_presenter.rb
spec/presenters/oregon_digital/iiif_presenter_spec.rb

Use the same idea from #work_presenters for #file_set_presenters

---

config/initializers/bulkrax.rb

Bulkrax patch from v5.1

---

config/initializers/bulkrax.rb

cleaning up method calls

---

config/initializers/bulkrax.rb

fieldname conversion

---

lib/tasks/oregon_digital/daily_email.rake

Add in a corrective description to `daily_email` rake task.

Fix description on rake task

---

app/views/oregon_digital/about/use.html.erb

Add in the revise part of `table of contents` to match a revision did earlier in one of the other PR.

Add in revise to the table of contents

---

lib/tasks/oregon_digital/daily_email.rake

Fix the grammar mistake in the task description.

Fix grammar mistake

---

app/views/shared/_footer.html.erb

Revise the footer with the updated footer note.

Re-edit footer

---

app/assets/stylesheets/oregon_digital/_home-page.scss
app/views/hyrax/homepage/_home_content.html.erb

Revise the link on the title to add more spacing.

Revise the feature collection section

---

lib/hyrax/controlled_vocabularies/location.rb
spec/hyrax/controlled_vocabularies/location_spec.rb
spec/workers/fetch_graph_worker_spec.rb

Add error catch to location label fetching

---

app/controllers/users/sessions_controller.rb

Make sure a user exists before checking for deactivation

---

app/assets/stylesheets/oregon_digital/explore_collections/_showcase.scss
app/views/hyrax/collections/show.html.erb

Add in a button to go to the `edit` section for Collection rather than going to the `Dashboard`.

Add in an edit button to Collection page

---

app/authorities/qa/authorities/extended_geonames.rb

`FEATURE` - Add in a way to search on webform locations fields (Location, Ranger District, Water Basin, Place of Production, Publication Place) with the `URI` or the `ID` of the GeoNames' Location.

Add searchable with URI

---

app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/_metadata.html.erb

Two column metadata fix

---

app/assets/stylesheets/oregon_digital/_buttons.scss

`FEATURE:` Add in to remove first item in the `Subject Term`.

Change CSS to display remove button for Subject

---

app/controllers/hyrax/homepage_controller.rb
spec/controllers/hyrax/homepage_controller_spec.rb
spec/system/homepage_accessibility_spec.rb

@wickr For the home page explore collection issues this morning

Prevent user collections and use correct collection sort on homepage

---

Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/bulkrax/filter_bulkrax.js
app/views/bulkrax/exporters/index.html.erb
app/views/bulkrax/importers/index.html.erb

Overriding the original layout to add in default sorting for both the `importer` & `exporter` for Bulkrax.

Add in default sorting to export & import

---

app/controllers/bulkrax/importers_controller.rb
app/views/bulkrax/importers/show.html.erb
config/routes.rb

Add in a way to fetch the importer file and make easy access to get the file out of import

Add in download button for importer

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb

closes #1133 
Added missing filter to Collection and Institution facets:

Add az filter to Collection and Institution facets

---

app/controllers/oregon_digital/oembeds_controller.rb
app/models/ability.rb
app/models/concerns/oregon_digital/ability/work_create_ability.rb
app/models/concerns/oregon_digital/ability/work_delete_ability.rb
app/models/concerns/oregon_digital/ability/work_download_ability.rb
app/models/concerns/oregon_digital/ability/work_show_ability.rb

Work for #1662 
Include Valkyrie resources in permissions/abilities

Get abilities and permissions valkyrie ready

---

app/controllers/oregon_digital/oembeds_controller.rb
app/models/ability.rb
app/models/concerns/oregon_digital/ability/work_create_ability.rb
app/models/concerns/oregon_digital/ability/work_delete_ability.rb
app/models/concerns/oregon_digital/ability/work_download_ability.rb
app/models/concerns/oregon_digital/ability/work_show_ability.rb

Reverts OregonDigital/OD2#2963

Revert "Get abilities and permissions valkyrie ready"

---

app/controllers/concerns/oregon_digital/works_controller_behavior.rb
app/controllers/oregon_digital/iiif_manifest_v2_controller.rb
app/controllers/oregon_digital/reviews_controller.rb
app/helpers/oregon_digital/citations_behaviors/formatters/apa_formatter.rb
app/helpers/oregon_digital/citations_behaviors/formatters/chicago_formatter.rb
app/helpers/oregon_digital/citations_behaviors/formatters/mla_formatter.rb
app/indexers/oregon_digital/deep_indexing_service.rb
app/jobs/bulk_approve_job.rb
app/jobs/oregon_digital/permission_change_propagation_job.rb
app/models/oembed_error.rb
app/parsers/bulkrax/bagit_complex_parser.rb
app/presenters/oregon_digital/collection_presenter.rb
app/views/hyrax/base/_show_actions.html.erb
app/workers/fetch_graph_worker.rb
app/workers/reindex_chunk_worker.rb
app/workers/reindex_one_lite.rb
app/workers/reindex_worker.rb
config/initializers/hacks/hyrax_collections_controller_behavior.rb
lib/tasks/migration/bulk_approve.rake
lib/tasks/oregon_digital/daily_email.rake
spec/jobs/oregon_digital/permission_change_propagation_job_spec.rb
spec/tasks/migration/rake_spec.rb

Reverts OregonDigital/OD2#2954

Revert "Valkyrize round 1"

---

app/search_builders/oregon_digital/only_non_user_collections_behavior.rb
build/firstrun.sh
config/initializers/hacks/hyrax_collections_members_controller.rb
lib/tasks/oregon_digital/create_admin_sets.rake
spec/controllers/hyrax/homepage_controller_spec.rb
spec/controllers/oregon_digital/explore_collections_controller_spec.rb
spec/factories/collection_type.rb
spec/features/blacklight_advanced_search_form_spec.rb
spec/search_builders/oregon_digital/non_user_collections_search_builder_spec.rb
spec/system/homepage_accessibility_spec.rb
spec/system/search_accessibility_spec.rb

Fixes OAI sets showing on the homepage and search results

Remove OAI sets from search and homepage

---

lib/tasks/oregon_digital/create_collections.rake

We need to grab a user here for the service to work. This should create the permissions for a freshly saved collection.

Add collection permissions creation after save

---

config/initializers/bulkrax.rb

use fieldhash_csv for visibility change

---

config/environments/development.rb
config/environments/production.rb

Fix psych disallowed

---

app/views/oregon_digital/about/recommend.html.erb

`FIXED:` - Add in the grammar fix after review on the recommendation section on the help guide.

Fix grammar on recommendation section

---

app/assets/stylesheets/oregon_digital/_home-page.scss
app/views/hyrax/homepage/_home_content.html.erb

updates with media query and realign chevron

---

app/assets/stylesheets/oregon_digital/_buttons.scss

`CSS` - Fix the css displaying box for `subject area`.

Fix the display of subject area

---

.yarnrc
package.json
yarn.lock

`UPDATE` - Add update to the yarn file for the security update.

Add update to the yarn file to fix some security update

---

app/services/concerns/oregon_digital/streaming_download_behavior.rb
app/services/oregon_digital/collection_streamer.rb
app/views/hyrax/collections/show.html.erb
config/initializers/hacks/hyrax_collections_controller_behavior.rb
config/routes.rb
spec/services/oregon_digital/collection_streamer_spec.rb

`FEATURE:` Fix a bug that did not display the download button to the collection.

Fix the download collection

---

app/models/concerns/oregon_digital/ability/work_download_ability.rb

Validate #uo_download_restricted? inputs

---

app/views/hyrax/collections/show.html.erb

`BUG FIX` - Add in another check status to make sure that `user_collection` are only collection for download.

Add in a check status for download button

---

app/views/catalog/_facet_limit.html.erb

Remove old facet sorting code

---

config/authorities/resource_types.yml
config/schema_org.yml

`FEATURE:` Update the facet to make some of the wording to make it fit better and easier to understand. In this scenario is the `resources_type` facet to display `moving image => video` and `sound => audio`.

Update YML file to reflect changes to facet

---

config/initializers/bulkrax.rb

fix constant

---

app/jobs/oregon_digital/verify_work_job.rb
app/services/oregon_digital/batch_verification_service.rb
app/services/oregon_digital/verify_derivatives_service.rb
app/services/oregon_digital/verify_service.rb
app/services/oregon_digital/verify_work_service.rb
config/environments/development.rb
config/environments/test.rb
spec/jobs/oregon_digital/verify_work_job_spec.rb
spec/services/oregon_digital/batch_verification_service_spec.rb
spec/services/oregon_digital/verify_work_service_spec.rb

Verify classes

---

app/views/oregon_digital/about/_sidebar.html.erb
app/views/shared/_footer.html.erb

`UPDATE:` Fix the consistency on the browser notice for OD2 viewing.

Fix browser notice consistent

---

app/jobs/oregon_digital/grant_edit_group_job.rb

Add GrantEditGroupJob.

---

app/models/concerns/oregon_digital/errors.rb
app/models/concerns/oregon_digital/work_behavior.rb
app/services/oregon_digital/verify_work_service.rb
config/initializers/hacks/hyrax_resource_patches.rb
spec/models/concerns/oregon_digital/errors_spec.rb
spec/services/oregon_digital/verify_work_service_spec.rb

add errors behavior to hyrax resource

---

app/controllers/oregon_digital/iiif_manifest_v2_controller.rb
app/presenters/oregon_digital/iiif_v2_presenter.rb

fixes #3040 
Screenshot of working IIIF manifest v2 page:

Resolve IIIF manifest v2 errors

---

config/initializers/bulkrax.rb

Fixes #3077 
This edits the bulkrax overrides. When its pulling data from the CSV it checks the key for keys that require an integer and casts it.

adds code to transform datatype for ingest

---

app/controllers/concerns/oregon_digital/importer_controller_behavior.rb
app/views/bulkrax/importers/show.html.erb
app/views/oregon_digital/importer_verification/_verify.html.erb
app/views/oregon_digital/importer_verification/show_errors.html.erb
config/initializers/bulkrax.rb
config/routes.rb
spec/controllers/bulkrax/importers_controller_spec.rb

Verify gui

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
app/helpers/oregon_digital/hyrax_helper_behavior.rb
app/indexers/concerns/oregon_digital/indexing_dates_behavior.rb
app/indexers/generic_indexer.rb
app/views/catalog/_facet_limit.html.erb
config/solr/conf/schema.xml

Reverts OregonDigital/OD2#3037

Revert "Downcase all facet values for better a-z sorting"

---

app/controllers/concerns/oregon_digital/importer_controller_behavior.rb
spec/controllers/bulkrax/importers_controller_spec.rb

fixes #3031 
adds logic to handle empty results from solr query and object not found error from valkyrie

add existence handling

---

app/controllers/concerns/oregon_digital/importer_controller_behavior.rb
app/helpers/oregon_digital/sidekiq_helper.rb
app/jobs/oregon_digital/verify_work_job.rb
app/views/oregon_digital/importer_verification/show_errors.html.erb
config/initializers/sidekiq.rb
spec/controllers/bulkrax/importers_controller_spec.rb

fixes #3114 
should probably merge 3113 first and I will rebase

Add sidekiq status

---

config/environments/development.rb
config/environments/production.rb
config/initializers/bulkrax.rb

limit importers

---

app/controllers/concerns/oregon_digital/importer_controller_behavior.rb
spec/controllers/bulkrax/importers_controller_spec.rb

view expects hash

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
app/models/concerns/oregon_digital/generic_metadata.rb
config/locales/hyrax.en.yml
config/locales/hyrax.es.yml
config/locales/hyrax.fr.yml
config/locales/hyrax.it.yml
config/locales/hyrax.pt-BR.yml

Add Identifier search field for Advanced Search.

---

app/forms/hyrax/generic_form.rb
app/forms/oregon_digital/forms/collection_form.rb
app/views/hyrax/collections/show.html.erb
spec/forms/oregon_digital/forms/collection_form_spec.rb

Reverts OregonDigital/OD2#3133

Revert "Small fixes and normalization"

---

app/models/concerns/oregon_digital/document_metadata.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/models/concerns/oregon_digital/image_metadata.rb
app/models/concerns/oregon_digital/video_metadata.rb
app/views/oregon_digital/base/_local_contexts.html.erb

`FEATURE:` Add in update to the `works` and allow it to appear on the other works form.

Add in LC to other work models

---

app/controllers/concerns/oregon_digital/aspace_digital_object_export_behavior.rb
app/models/concerns/oregon_digital/uri_methods.rb
app/models/oregon_digital/aspace_digital_object.rb
app/views/bulkrax/importers/show.html.erb
app/views/oregon_digital/importer/_digobj_export.html.erb
config/initializers/bulkrax.rb
config/routes.rb

Digital obj export

---

app/controllers/concerns/oregon_digital/export_collection_members_behavior.rb
app/jobs/oregon_digital/export_collection_members_job.rb
app/mailers/oregon_digital/export_mailer.rb
app/services/oregon_digital/export_collection_members_service.rb
app/views/hyrax/collections/show.html.erb
app/views/oregon_digital/export_mailer/export_ready.html.erb
config/environments/development.rb
config/environments/production.rb
config/initializers/hacks/hyrax_collections_controller.rb
config/routes.rb

Export rdf

---

app/views/oregon_digital/about/harmful.html.erb

`UPDATE:` Add in the new link to the UO harmful content URL.

Add an updated link to the harmful content

---

app/views/oregon_digital/about/takedown.html.erb

`UPDATE:` Add in another fix towards the broken link on OD2

Update another broken link area

---

app/factories/bulkrax/oregon_digital_object_factory.rb
config/initializers/bulkrax.rb

add oembed_urls to bulkrax

---

lib/oregon_digital/controlled_vocabularies/subject.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/homosaurus.rb
lib/oregon_digital/triplestore.rb
spec/authorities/qa/authorities/subject_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/homosaurus_spec.rb

`METADATA:` Add in the `homosaurus CV` into OD2 as part of the `subject cv`.

Add in Homosaurus to the subject field

---

app/authorities/qa/authorities/subject.rb
lib/oregon_digital/controlled_vocabularies/resource.rb
lib/oregon_digital/controlled_vocabularies/subject.rb
lib/oregon_digital/controlled_vocabularies/vocabularies/bne_authority_file.rb
lib/oregon_digital/triplestore.rb
spec/authorities/qa/authorities/subject_spec.rb
spec/oregon_digital/controlled_vocabularies/vocabularies/bne_authority_file_spec.rb

`METADATA:` Add in a new `cv` to the `subject` field called `BNE Authority File`.

Add BNE Authority File CV to the Subject

---

lib/oregon_digital/controlled_vocabularies/resource.rb

`UPDATE:` Parse out special `esp` label when encounter `BNE Authority File`.
fixes #3164

Add in special case to filter out for BNE

---

lib/oregon_digital/triplestore.rb

`UPDATE:` Fix the `gsub` problem that method did not exist and double check URL and just need to append `.jsonld`
fixes #3164

Fix the string iterpolation on BNE

---

config/initializers/bulkrax.rb

test for index_field_mapper

---

app/models/solr_document.rb

Fix and simplify multidocument solr find

---

Dockerfile
Gemfile
Gemfile.lock
config/locales/hyrax.en.yml

This updates the dockerfile, removes willow_sword and updates a form

Fresh Install Plus Form Update

---

app/mailers/oregon_digital/notification_mailer.rb
app/views/oregon_digital/notification_mailer/notification_email.html.erb
lib/oregon_digital/notification.rb
lib/tasks/oregon_digital/daily_email.rake
spec/mailers/oregon_digital/notification_mailer_spec.rb
spec/oregon_digital/notification_spec.rb

fixes #1562 
This ended up being a rework of existing code that doesn't seem to have been put into operation yet.
Fetches assets using a solr query with workflow and  time fields
Also does a simple check based on thumbnail path to see if derivatives are completed
Assumes that for now we just notify the depositor; also assumes that notifications are for newly created works (the time window ends X seconds after system_create time).

Daily notify

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb

Sorts on prefix a..z instead of A..Z

---

config/solr/conf/solrconfig.xml

This will require a solr configset update & reindex
#3210

Add /terms endpoint to solr for Hyrax statistics

---

app/assets/stylesheets/blacklight/facet_overrides.scss
app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
app/views/catalog/_facets.html.erb
config/locales/blacklight.en.yml

`FEATURE:` Update the facet filter on the search page to filter out primary & secondary facets to display.
fixes #1132

Sort out facets in filter section

---

Gemfile.lock
config/environments/development.rb
config/sidekiq.yml
docker-compose.yml

Improves/fixes:
- Error w/ logger level preventing rails/rake tasks
- Use new terminology for web_console
- add a reindex queue to sidekiq
- disable valkyrie until we can generate real valkyrie resources

A couple configuration tweaks for local development

---

app/assets/stylesheets/oregon_digital/_buttons.scss
app/assets/stylesheets/oregon_digital/_search.scss
app/assets/stylesheets/oregon_digital/explore_collections/_buttons.scss
app/assets/stylesheets/oregon_digital/explore_collections/_masonry_view.scss
app/assets/stylesheets/oregon_digital/explore_collections/_showcase.scss
app/controllers/oregon_digital/explore_collections_controller.rb
app/views/_masthead.html.erb
app/views/oregon_digital/explore_collections/_explore_tabs.html.erb
app/views/oregon_digital/explore_collections/_index_masonry.html.erb

Closes #3216 
- Updates button text format on Explore tab buttons
- Adjusts triangle indicator so that it is visible on active tab
- Adds missing translation in 'My Collections' breadcrumb
- Adjusts responsive layout breakpoints
- Fixes masonry view item title text
- Adjusts pagination layout and colors
- Missing table view
- Missing view type buttons
- Masonry view icon not being set properly through `config.view.masonry.icon_class`
- Missing sort fields
These issues seem to be related to changes in setting config in `app/controllers/oregon_digital/explore_collections_controller.rb`. Once the issues have been resolved, I can go back in and update the bootstrap/CSS.

Explore Collections bootstrap upgrade

---

app/controllers/catalog_controller.rb
app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb
app/controllers/oregon_digital/explore_collections_controller.rb
app/views/catalog/_constraints.html.erb
app/views/catalog/_constraints_element.html.erb
app/views/catalog/_per_page_widget.html.erb
app/views/catalog/_search_form.html.erb
app/views/catalog/_sort_widget.html.erb
app/views/oregon_digital/explore_collections/_per_page_widget.html.erb

Only a little bit of fixup, mostly just getting things to display similarly
Explore collections page is next

Blacklight Search Constraints

---

app/controllers/concerns/oregon_digital/aspace_digital_object_export_behavior.rb
app/models/oregon_digital/aspace_digital_object.rb
spec/models/oregon_digital/aspace_digital_object_spec.rb

Fix aspace do export

---

app/assets/stylesheets/oregon_digital/_home-page.scss

`UPDATE:` Remove a line in CSS to fix the image display in the `feature_collection`

Remove CSS to fix the display of thumbnail

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/oregon_digital/_buttons.scss
app/presenters/oregon_digital/permission_badge.rb
app/views/hyrax/collections/_show_document_list_row.html.erb
app/views/hyrax/dashboard/works/_list_works.html.erb
app/views/hyrax/my/_search_form.html.erb
app/views/hyrax/my/works/_list_works.html.erb
app/views/layouts/hyrax/dashboard.html.erb
app/views/oregon_digital/oembeds/_table.html.erb

Work on #3327 for my/all works pages

Dashboard works page Bootstrap/CSS

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/oregon_digital/_sign_up.scss
app/assets/stylesheets/oregon_digital/_work-show.scss
app/views/hyrax/base/_show_actions.html.erb
app/views/hyrax/base/_work_title.html.erb
app/views/hyrax/base/show.html.erb

Work show container and action buttons

---

app/mailers/oregon_digital/failed_fetch_mailer.rb
app/views/oregon_digital/failed_fetch_mailer/failed_fetch_email.html.erb
app/workers/fetch_graph_worker.rb
lib/oregon_digital/failed_fetch_notification.rb
lib/tasks/oregon_digital/daily_email.rake
spec/mailers/oregon_digital/failed_fetch_mailer_spec.rb

`UPDATE:` Update the script to `failed_fetch` to make sure it handle edge cases on creating files.

Update script on Failed Fetch

---

app/models/concerns/oregon_digital/document_metadata.rb
app/models/concerns/oregon_digital/generic_metadata.rb
app/models/concerns/oregon_digital/image_metadata.rb
config/locales/hyrax.de.yml
config/locales/hyrax.en.yml
config/locales/hyrax.es.yml
config/locales/hyrax.fr.yml
config/locales/hyrax.it.yml
config/locales/hyrax.pt-BR.yml
config/locales/hyrax.zh.yml
spec/system/create_audio_spec.rb
spec/system/create_document_spec.rb
spec/system/create_generic_spec.rb
spec/system/create_image_spec.rb
spec/system/create_video_spec.rb

`UPDATE:` Update the ingest form (`edit/create form`) of OD2 to the requirement specifically ask.
fixes #1713 
TASKS:

Update forms with the requirements

---

app/assets/stylesheets/oregon_digital/_work-show.scss
app/controllers/concerns/oregon_digital/work_relation_pagination_behavior.rb
app/views/catalog/_document_gallery.html.erb
app/views/hyrax/base/_index_gallery.html.erb

Fix related items and similar rows

---

app/indexers/generic_indexer.rb

Need coll.title.first to lose the brackets
Fixes #3355

Fix Collection title label indexing

---

app/models/concerns/oregon_digital/uri_methods.rb
spec/models/concerns/oregon_digital/uri_methods_spec.rb
spec/models/oregon_digital/aspace_digital_object_spec.rb

fixes #3151
replaces calls to URI.join, additional tests

stop using URI.join

---

config/initializers/_hyrax.rb
docker-compose.yml

fixes #3371 
Note that in order to get this working locally:
set the variable
clear out tmp/cache/assets
restart

raise maxfilesize

---

app/controllers/concerns/oregon_digital/blacklight_config_behavior.rb

All "More" Facets available as well

removes blacklight config conflict

---

app/factories/bulkrax/oregon_digital_object_factory.rb
config/initializers/bulkrax.rb

`BUG:` Create an update to the `Bulkrax` importer to accept the two new fields in Accessibility Feature and Summary.

Create a manual importer for Accessibilities

---

app/models/concerns/oregon_digital/collection_metadata.rb
app/models/concerns/oregon_digital/generic_metadata.rb
config/initializers/bulkrax.rb

`UPDATE:` Make more update to `accessibility` schema based on feedback

Update small predicate & Bulkrax

---

config/initializers/bulkrax.rb

`UPDATE:` Revert some code for Schema after having another talk

Revert code on Schema Bulkrax

---

app/views/oregon_digital/about/privacy.html.erb

`UPDATE:` Add in a new section under `Personal Info` with some updated text.

Add in an updated area in Policy
